/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_BL_FLASH_DRV_H
#define _MOCK_BL_FLASH_DRV_H

#include "unity.h"
#include "bl_flash_drv.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_bl_flash_drv_Init(void);
void mock_bl_flash_drv_Destroy(void);
void mock_bl_flash_drv_Verify(void);




#define FLASH_waitBusy_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("FLASH_waitBusy requires _Ignore (not AndReturn)");
#define FLASH_waitBusy_Ignore() FLASH_waitBusy_CMockIgnore()
void FLASH_waitBusy_CMockIgnore(void);
#define FLASH_waitBusy_StopIgnore() FLASH_waitBusy_CMockStopIgnore()
void FLASH_waitBusy_CMockStopIgnore(void);
#define FLASH_waitBusy_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("FLASH_waitBusy requires _Expect (not AndReturn)");
#define FLASH_waitBusy_Expect() FLASH_waitBusy_CMockExpect(__LINE__)
void FLASH_waitBusy_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_FLASH_waitBusy_CALLBACK)(int cmock_num_calls);
void FLASH_waitBusy_AddCallback(CMOCK_FLASH_waitBusy_CALLBACK Callback);
void FLASH_waitBusy_Stub(CMOCK_FLASH_waitBusy_CALLBACK Callback);
#define FLASH_waitBusy_StubWithCallback FLASH_waitBusy_Stub
#define FLASH_unlock_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("FLASH_unlock requires _Ignore (not AndReturn)");
#define FLASH_unlock_Ignore() FLASH_unlock_CMockIgnore()
void FLASH_unlock_CMockIgnore(void);
#define FLASH_unlock_StopIgnore() FLASH_unlock_CMockStopIgnore()
void FLASH_unlock_CMockStopIgnore(void);
#define FLASH_unlock_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("FLASH_unlock requires _Expect (not AndReturn)");
#define FLASH_unlock_Expect() FLASH_unlock_CMockExpect(__LINE__)
void FLASH_unlock_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_FLASH_unlock_CALLBACK)(int cmock_num_calls);
void FLASH_unlock_AddCallback(CMOCK_FLASH_unlock_CALLBACK Callback);
void FLASH_unlock_Stub(CMOCK_FLASH_unlock_CALLBACK Callback);
#define FLASH_unlock_StubWithCallback FLASH_unlock_Stub
#define FLASH_lock_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("FLASH_lock requires _Ignore (not AndReturn)");
#define FLASH_lock_Ignore() FLASH_lock_CMockIgnore()
void FLASH_lock_CMockIgnore(void);
#define FLASH_lock_StopIgnore() FLASH_lock_CMockStopIgnore()
void FLASH_lock_CMockStopIgnore(void);
#define FLASH_lock_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("FLASH_lock requires _Expect (not AndReturn)");
#define FLASH_lock_Expect() FLASH_lock_CMockExpect(__LINE__)
void FLASH_lock_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_FLASH_lock_CALLBACK)(int cmock_num_calls);
void FLASH_lock_AddCallback(CMOCK_FLASH_lock_CALLBACK Callback);
void FLASH_lock_Stub(CMOCK_FLASH_lock_CALLBACK Callback);
#define FLASH_lock_StubWithCallback FLASH_lock_Stub
#define FLASH_erasePage_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("FLASH_erasePage requires _Ignore (not AndReturn)");
#define FLASH_erasePage_Ignore() FLASH_erasePage_CMockIgnore()
void FLASH_erasePage_CMockIgnore(void);
#define FLASH_erasePage_StopIgnore() FLASH_erasePage_CMockStopIgnore()
void FLASH_erasePage_CMockStopIgnore(void);
#define FLASH_erasePage_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("FLASH_erasePage requires _ExpectAnyArgs (not AndReturn)");
#define FLASH_erasePage_ExpectAnyArgs() FLASH_erasePage_CMockExpectAnyArgs(__LINE__)
void FLASH_erasePage_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define FLASH_erasePage_ExpectAndReturn(flash_page_no, cmock_retval) TEST_FAIL_MESSAGE("FLASH_erasePage requires _Expect (not AndReturn)");
#define FLASH_erasePage_Expect(flash_page_no) FLASH_erasePage_CMockExpect(__LINE__, flash_page_no)
void FLASH_erasePage_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t flash_page_no);
typedef void (* CMOCK_FLASH_erasePage_CALLBACK)(uint32_t flash_page_no, int cmock_num_calls);
void FLASH_erasePage_AddCallback(CMOCK_FLASH_erasePage_CALLBACK Callback);
void FLASH_erasePage_Stub(CMOCK_FLASH_erasePage_CALLBACK Callback);
#define FLASH_erasePage_StubWithCallback FLASH_erasePage_Stub
#define FLASH_write_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("FLASH_write requires _Ignore (not AndReturn)");
#define FLASH_write_Ignore() FLASH_write_CMockIgnore()
void FLASH_write_CMockIgnore(void);
#define FLASH_write_StopIgnore() FLASH_write_CMockStopIgnore()
void FLASH_write_CMockStopIgnore(void);
#define FLASH_write_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("FLASH_write requires _ExpectAnyArgs (not AndReturn)");
#define FLASH_write_ExpectAnyArgs() FLASH_write_CMockExpectAnyArgs(__LINE__)
void FLASH_write_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define FLASH_write_ExpectAndReturn(addr, data, dataLen, cmock_retval) TEST_FAIL_MESSAGE("FLASH_write requires _Expect (not AndReturn)");
#define FLASH_write_Expect(addr, data, dataLen) FLASH_write_CMockExpect(__LINE__, addr, data, dataLen)
void FLASH_write_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t addr, uint32_t const* data, size_t dataLen);
typedef void (* CMOCK_FLASH_write_CALLBACK)(uint32_t addr, uint32_t const* data, size_t dataLen, int cmock_num_calls);
void FLASH_write_AddCallback(CMOCK_FLASH_write_CALLBACK Callback);
void FLASH_write_Stub(CMOCK_FLASH_write_CALLBACK Callback);
#define FLASH_write_StubWithCallback FLASH_write_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
