/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_crc_api.h"

static const char* CMockString_CRC_add_byte = "CRC_add_byte";
static const char* CMockString_CRC_add_byte_tab = "CRC_add_byte_tab";
static const char* CMockString_CRC_hw_init = "CRC_hw_init";
static const char* CMockString_CRC_init = "CRC_init";
static const char* CMockString_CRC_result = "CRC_result";
static const char* CMockString_b = "b";
static const char* CMockString_crc = "crc";
static const char* CMockString_data = "data";
static const char* CMockString_dataLen = "dataLen";

typedef struct _CMOCK_CRC_hw_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_CRC_hw_init_CALL_INSTANCE;

typedef struct _CMOCK_CRC_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;

} CMOCK_CRC_init_CALL_INSTANCE;

typedef struct _CMOCK_CRC_add_byte_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;
  uint32_t Expected_crc;
  uint8_t Expected_b;

} CMOCK_CRC_add_byte_CALL_INSTANCE;

typedef struct _CMOCK_CRC_add_byte_tab_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;
  uint32_t Expected_crc;
  uint8_t const* Expected_data;
  size_t Expected_dataLen;

} CMOCK_CRC_add_byte_tab_CALL_INSTANCE;

typedef struct _CMOCK_CRC_result_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;
  uint32_t Expected_crc;

} CMOCK_CRC_result_CALL_INSTANCE;

static struct mock_crc_apiInstance
{
  char CRC_hw_init_IgnoreBool;
  char CRC_hw_init_CallbackBool;
  CMOCK_CRC_hw_init_CALLBACK CRC_hw_init_CallbackFunctionPointer;
  int CRC_hw_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE CRC_hw_init_CallInstance;
  char CRC_init_IgnoreBool;
  uint32_t CRC_init_FinalReturn;
  char CRC_init_CallbackBool;
  CMOCK_CRC_init_CALLBACK CRC_init_CallbackFunctionPointer;
  int CRC_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE CRC_init_CallInstance;
  char CRC_add_byte_IgnoreBool;
  uint32_t CRC_add_byte_FinalReturn;
  char CRC_add_byte_CallbackBool;
  CMOCK_CRC_add_byte_CALLBACK CRC_add_byte_CallbackFunctionPointer;
  int CRC_add_byte_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE CRC_add_byte_CallInstance;
  char CRC_add_byte_tab_IgnoreBool;
  uint32_t CRC_add_byte_tab_FinalReturn;
  char CRC_add_byte_tab_CallbackBool;
  CMOCK_CRC_add_byte_tab_CALLBACK CRC_add_byte_tab_CallbackFunctionPointer;
  int CRC_add_byte_tab_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE CRC_add_byte_tab_CallInstance;
  char CRC_result_IgnoreBool;
  uint32_t CRC_result_FinalReturn;
  char CRC_result_CallbackBool;
  CMOCK_CRC_result_CALLBACK CRC_result_CallbackFunctionPointer;
  int CRC_result_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE CRC_result_CallInstance;
} Mock;


void mock_crc_api_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.CRC_hw_init_CallInstance;
  if (Mock.CRC_hw_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_CRC_hw_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.CRC_hw_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.CRC_init_CallInstance;
  if (Mock.CRC_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_CRC_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.CRC_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.CRC_add_byte_CallInstance;
  if (Mock.CRC_add_byte_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_CRC_add_byte);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.CRC_add_byte_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.CRC_add_byte_tab_CallInstance;
  if (Mock.CRC_add_byte_tab_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_CRC_add_byte_tab);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.CRC_add_byte_tab_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.CRC_result_CallInstance;
  if (Mock.CRC_result_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_CRC_result);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.CRC_result_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_crc_api_Init(void)
{
  mock_crc_api_Destroy();
}

void mock_crc_api_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void CRC_hw_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_CRC_hw_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_CRC_hw_init);
  cmock_call_instance = (CMOCK_CRC_hw_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.CRC_hw_init_CallInstance);
  Mock.CRC_hw_init_CallInstance = CMock_Guts_MemNext(Mock.CRC_hw_init_CallInstance);
  if (Mock.CRC_hw_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.CRC_hw_init_CallbackBool &&
      Mock.CRC_hw_init_CallbackFunctionPointer != NULL)
  {
    Mock.CRC_hw_init_CallbackFunctionPointer(Mock.CRC_hw_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.CRC_hw_init_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_CRC_hw_init);
    Mock.CRC_hw_init_CallbackFunctionPointer(Mock.CRC_hw_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CRC_hw_init_CMockIgnore(void)
{
  Mock.CRC_hw_init_IgnoreBool = (char)1;
}

void CRC_hw_init_CMockStopIgnore(void)
{
  Mock.CRC_hw_init_IgnoreBool = (char)0;
}

void CRC_hw_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CRC_hw_init_CALL_INSTANCE));
  CMOCK_CRC_hw_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_CRC_hw_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CRC_hw_init_CallInstance = CMock_Guts_MemChain(Mock.CRC_hw_init_CallInstance, cmock_guts_index);
  Mock.CRC_hw_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void CRC_hw_init_AddCallback(CMOCK_CRC_hw_init_CALLBACK Callback)
{
  Mock.CRC_hw_init_IgnoreBool = (char)0;
  Mock.CRC_hw_init_CallbackBool = (char)1;
  Mock.CRC_hw_init_CallbackFunctionPointer = Callback;
}

void CRC_hw_init_Stub(CMOCK_CRC_hw_init_CALLBACK Callback)
{
  Mock.CRC_hw_init_IgnoreBool = (char)0;
  Mock.CRC_hw_init_CallbackBool = (char)0;
  Mock.CRC_hw_init_CallbackFunctionPointer = Callback;
}

uint32_t CRC_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_CRC_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_CRC_init);
  cmock_call_instance = (CMOCK_CRC_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.CRC_init_CallInstance);
  Mock.CRC_init_CallInstance = CMock_Guts_MemNext(Mock.CRC_init_CallInstance);
  if (Mock.CRC_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.CRC_init_FinalReturn;
    Mock.CRC_init_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.CRC_init_CallbackBool &&
      Mock.CRC_init_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.CRC_init_CallbackFunctionPointer(Mock.CRC_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.CRC_init_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_CRC_init);
    cmock_call_instance->ReturnVal = Mock.CRC_init_CallbackFunctionPointer(Mock.CRC_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CRC_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CRC_init_CALL_INSTANCE));
  CMOCK_CRC_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_CRC_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CRC_init_CallInstance = CMock_Guts_MemChain(Mock.CRC_init_CallInstance, cmock_guts_index);
  Mock.CRC_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.CRC_init_IgnoreBool = (char)1;
}

void CRC_init_CMockStopIgnore(void)
{
  if(Mock.CRC_init_IgnoreBool)
    Mock.CRC_init_CallInstance = CMock_Guts_MemNext(Mock.CRC_init_CallInstance);
  Mock.CRC_init_IgnoreBool = (char)0;
}

void CRC_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CRC_init_CALL_INSTANCE));
  CMOCK_CRC_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_CRC_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CRC_init_CallInstance = CMock_Guts_MemChain(Mock.CRC_init_CallInstance, cmock_guts_index);
  Mock.CRC_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void CRC_init_AddCallback(CMOCK_CRC_init_CALLBACK Callback)
{
  Mock.CRC_init_IgnoreBool = (char)0;
  Mock.CRC_init_CallbackBool = (char)1;
  Mock.CRC_init_CallbackFunctionPointer = Callback;
}

void CRC_init_Stub(CMOCK_CRC_init_CALLBACK Callback)
{
  Mock.CRC_init_IgnoreBool = (char)0;
  Mock.CRC_init_CallbackBool = (char)0;
  Mock.CRC_init_CallbackFunctionPointer = Callback;
}

uint32_t CRC_add_byte(uint32_t crc, uint8_t b)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_CRC_add_byte_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_CRC_add_byte);
  cmock_call_instance = (CMOCK_CRC_add_byte_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.CRC_add_byte_CallInstance);
  Mock.CRC_add_byte_CallInstance = CMock_Guts_MemNext(Mock.CRC_add_byte_CallInstance);
  if (Mock.CRC_add_byte_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.CRC_add_byte_FinalReturn;
    Mock.CRC_add_byte_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.CRC_add_byte_CallbackBool &&
      Mock.CRC_add_byte_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.CRC_add_byte_CallbackFunctionPointer(crc, b, Mock.CRC_add_byte_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_CRC_add_byte,CMockString_crc);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_crc, crc, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_CRC_add_byte,CMockString_b);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_b, b, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.CRC_add_byte_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_CRC_add_byte);
    cmock_call_instance->ReturnVal = Mock.CRC_add_byte_CallbackFunctionPointer(crc, b, Mock.CRC_add_byte_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_CRC_add_byte(CMOCK_CRC_add_byte_CALL_INSTANCE* cmock_call_instance, uint32_t crc, uint8_t b);
void CMockExpectParameters_CRC_add_byte(CMOCK_CRC_add_byte_CALL_INSTANCE* cmock_call_instance, uint32_t crc, uint8_t b)
{
  cmock_call_instance->Expected_crc = crc;
  cmock_call_instance->Expected_b = b;
}

void CRC_add_byte_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CRC_add_byte_CALL_INSTANCE));
  CMOCK_CRC_add_byte_CALL_INSTANCE* cmock_call_instance = (CMOCK_CRC_add_byte_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CRC_add_byte_CallInstance = CMock_Guts_MemChain(Mock.CRC_add_byte_CallInstance, cmock_guts_index);
  Mock.CRC_add_byte_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.CRC_add_byte_IgnoreBool = (char)1;
}

void CRC_add_byte_CMockStopIgnore(void)
{
  if(Mock.CRC_add_byte_IgnoreBool)
    Mock.CRC_add_byte_CallInstance = CMock_Guts_MemNext(Mock.CRC_add_byte_CallInstance);
  Mock.CRC_add_byte_IgnoreBool = (char)0;
}

void CRC_add_byte_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CRC_add_byte_CALL_INSTANCE));
  CMOCK_CRC_add_byte_CALL_INSTANCE* cmock_call_instance = (CMOCK_CRC_add_byte_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CRC_add_byte_CallInstance = CMock_Guts_MemChain(Mock.CRC_add_byte_CallInstance, cmock_guts_index);
  Mock.CRC_add_byte_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void CRC_add_byte_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t crc, uint8_t b, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CRC_add_byte_CALL_INSTANCE));
  CMOCK_CRC_add_byte_CALL_INSTANCE* cmock_call_instance = (CMOCK_CRC_add_byte_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CRC_add_byte_CallInstance = CMock_Guts_MemChain(Mock.CRC_add_byte_CallInstance, cmock_guts_index);
  Mock.CRC_add_byte_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_CRC_add_byte(cmock_call_instance, crc, b);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void CRC_add_byte_AddCallback(CMOCK_CRC_add_byte_CALLBACK Callback)
{
  Mock.CRC_add_byte_IgnoreBool = (char)0;
  Mock.CRC_add_byte_CallbackBool = (char)1;
  Mock.CRC_add_byte_CallbackFunctionPointer = Callback;
}

void CRC_add_byte_Stub(CMOCK_CRC_add_byte_CALLBACK Callback)
{
  Mock.CRC_add_byte_IgnoreBool = (char)0;
  Mock.CRC_add_byte_CallbackBool = (char)0;
  Mock.CRC_add_byte_CallbackFunctionPointer = Callback;
}

uint32_t CRC_add_byte_tab(uint32_t crc, uint8_t const* data, size_t dataLen)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_CRC_add_byte_tab_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_CRC_add_byte_tab);
  cmock_call_instance = (CMOCK_CRC_add_byte_tab_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.CRC_add_byte_tab_CallInstance);
  Mock.CRC_add_byte_tab_CallInstance = CMock_Guts_MemNext(Mock.CRC_add_byte_tab_CallInstance);
  if (Mock.CRC_add_byte_tab_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.CRC_add_byte_tab_FinalReturn;
    Mock.CRC_add_byte_tab_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.CRC_add_byte_tab_CallbackBool &&
      Mock.CRC_add_byte_tab_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.CRC_add_byte_tab_CallbackFunctionPointer(crc, data, dataLen, Mock.CRC_add_byte_tab_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_CRC_add_byte_tab,CMockString_crc);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_crc, crc, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_CRC_add_byte_tab,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_CRC_add_byte_tab,CMockString_dataLen);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_dataLen, &dataLen, sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.CRC_add_byte_tab_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_CRC_add_byte_tab);
    cmock_call_instance->ReturnVal = Mock.CRC_add_byte_tab_CallbackFunctionPointer(crc, data, dataLen, Mock.CRC_add_byte_tab_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_CRC_add_byte_tab(CMOCK_CRC_add_byte_tab_CALL_INSTANCE* cmock_call_instance, uint32_t crc, uint8_t const* data, size_t dataLen);
void CMockExpectParameters_CRC_add_byte_tab(CMOCK_CRC_add_byte_tab_CALL_INSTANCE* cmock_call_instance, uint32_t crc, uint8_t const* data, size_t dataLen)
{
  cmock_call_instance->Expected_crc = crc;
  cmock_call_instance->Expected_data = data;
  memcpy((void*)(&cmock_call_instance->Expected_dataLen), (const void*)(&dataLen),
         sizeof(size_t[sizeof(dataLen) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void CRC_add_byte_tab_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CRC_add_byte_tab_CALL_INSTANCE));
  CMOCK_CRC_add_byte_tab_CALL_INSTANCE* cmock_call_instance = (CMOCK_CRC_add_byte_tab_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CRC_add_byte_tab_CallInstance = CMock_Guts_MemChain(Mock.CRC_add_byte_tab_CallInstance, cmock_guts_index);
  Mock.CRC_add_byte_tab_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.CRC_add_byte_tab_IgnoreBool = (char)1;
}

void CRC_add_byte_tab_CMockStopIgnore(void)
{
  if(Mock.CRC_add_byte_tab_IgnoreBool)
    Mock.CRC_add_byte_tab_CallInstance = CMock_Guts_MemNext(Mock.CRC_add_byte_tab_CallInstance);
  Mock.CRC_add_byte_tab_IgnoreBool = (char)0;
}

void CRC_add_byte_tab_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CRC_add_byte_tab_CALL_INSTANCE));
  CMOCK_CRC_add_byte_tab_CALL_INSTANCE* cmock_call_instance = (CMOCK_CRC_add_byte_tab_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CRC_add_byte_tab_CallInstance = CMock_Guts_MemChain(Mock.CRC_add_byte_tab_CallInstance, cmock_guts_index);
  Mock.CRC_add_byte_tab_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void CRC_add_byte_tab_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t crc, uint8_t const* data, size_t dataLen, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CRC_add_byte_tab_CALL_INSTANCE));
  CMOCK_CRC_add_byte_tab_CALL_INSTANCE* cmock_call_instance = (CMOCK_CRC_add_byte_tab_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CRC_add_byte_tab_CallInstance = CMock_Guts_MemChain(Mock.CRC_add_byte_tab_CallInstance, cmock_guts_index);
  Mock.CRC_add_byte_tab_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_CRC_add_byte_tab(cmock_call_instance, crc, data, dataLen);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void CRC_add_byte_tab_AddCallback(CMOCK_CRC_add_byte_tab_CALLBACK Callback)
{
  Mock.CRC_add_byte_tab_IgnoreBool = (char)0;
  Mock.CRC_add_byte_tab_CallbackBool = (char)1;
  Mock.CRC_add_byte_tab_CallbackFunctionPointer = Callback;
}

void CRC_add_byte_tab_Stub(CMOCK_CRC_add_byte_tab_CALLBACK Callback)
{
  Mock.CRC_add_byte_tab_IgnoreBool = (char)0;
  Mock.CRC_add_byte_tab_CallbackBool = (char)0;
  Mock.CRC_add_byte_tab_CallbackFunctionPointer = Callback;
}

uint32_t CRC_result(uint32_t crc)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_CRC_result_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_CRC_result);
  cmock_call_instance = (CMOCK_CRC_result_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.CRC_result_CallInstance);
  Mock.CRC_result_CallInstance = CMock_Guts_MemNext(Mock.CRC_result_CallInstance);
  if (Mock.CRC_result_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.CRC_result_FinalReturn;
    Mock.CRC_result_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.CRC_result_CallbackBool &&
      Mock.CRC_result_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.CRC_result_CallbackFunctionPointer(crc, Mock.CRC_result_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_CRC_result,CMockString_crc);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_crc, crc, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.CRC_result_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_CRC_result);
    cmock_call_instance->ReturnVal = Mock.CRC_result_CallbackFunctionPointer(crc, Mock.CRC_result_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_CRC_result(CMOCK_CRC_result_CALL_INSTANCE* cmock_call_instance, uint32_t crc);
void CMockExpectParameters_CRC_result(CMOCK_CRC_result_CALL_INSTANCE* cmock_call_instance, uint32_t crc)
{
  cmock_call_instance->Expected_crc = crc;
}

void CRC_result_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CRC_result_CALL_INSTANCE));
  CMOCK_CRC_result_CALL_INSTANCE* cmock_call_instance = (CMOCK_CRC_result_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CRC_result_CallInstance = CMock_Guts_MemChain(Mock.CRC_result_CallInstance, cmock_guts_index);
  Mock.CRC_result_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.CRC_result_IgnoreBool = (char)1;
}

void CRC_result_CMockStopIgnore(void)
{
  if(Mock.CRC_result_IgnoreBool)
    Mock.CRC_result_CallInstance = CMock_Guts_MemNext(Mock.CRC_result_CallInstance);
  Mock.CRC_result_IgnoreBool = (char)0;
}

void CRC_result_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CRC_result_CALL_INSTANCE));
  CMOCK_CRC_result_CALL_INSTANCE* cmock_call_instance = (CMOCK_CRC_result_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CRC_result_CallInstance = CMock_Guts_MemChain(Mock.CRC_result_CallInstance, cmock_guts_index);
  Mock.CRC_result_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void CRC_result_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t crc, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CRC_result_CALL_INSTANCE));
  CMOCK_CRC_result_CALL_INSTANCE* cmock_call_instance = (CMOCK_CRC_result_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CRC_result_CallInstance = CMock_Guts_MemChain(Mock.CRC_result_CallInstance, cmock_guts_index);
  Mock.CRC_result_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_CRC_result(cmock_call_instance, crc);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void CRC_result_AddCallback(CMOCK_CRC_result_CALLBACK Callback)
{
  Mock.CRC_result_IgnoreBool = (char)0;
  Mock.CRC_result_CallbackBool = (char)1;
  Mock.CRC_result_CallbackFunctionPointer = Callback;
}

void CRC_result_Stub(CMOCK_CRC_result_CALLBACK Callback)
{
  Mock.CRC_result_IgnoreBool = (char)0;
  Mock.CRC_result_CallbackBool = (char)0;
  Mock.CRC_result_CallbackFunctionPointer = Callback;
}

