/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_bl_flash_drv.h"

static const char* CMockString_FLASH_erasePage = "FLASH_erasePage";
static const char* CMockString_FLASH_lock = "FLASH_lock";
static const char* CMockString_FLASH_unlock = "FLASH_unlock";
static const char* CMockString_FLASH_waitBusy = "FLASH_waitBusy";
static const char* CMockString_FLASH_write = "FLASH_write";
static const char* CMockString_addr = "addr";
static const char* CMockString_data = "data";
static const char* CMockString_dataLen = "dataLen";
static const char* CMockString_flash_page_no = "flash_page_no";

typedef struct _CMOCK_FLASH_waitBusy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_FLASH_waitBusy_CALL_INSTANCE;

typedef struct _CMOCK_FLASH_unlock_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_FLASH_unlock_CALL_INSTANCE;

typedef struct _CMOCK_FLASH_lock_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_FLASH_lock_CALL_INSTANCE;

typedef struct _CMOCK_FLASH_erasePage_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t Expected_flash_page_no;

} CMOCK_FLASH_erasePage_CALL_INSTANCE;

typedef struct _CMOCK_FLASH_write_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t Expected_addr;
  uint32_t const* Expected_data;
  size_t Expected_dataLen;

} CMOCK_FLASH_write_CALL_INSTANCE;

static struct mock_bl_flash_drvInstance
{
  char FLASH_waitBusy_IgnoreBool;
  char FLASH_waitBusy_CallbackBool;
  CMOCK_FLASH_waitBusy_CALLBACK FLASH_waitBusy_CallbackFunctionPointer;
  int FLASH_waitBusy_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE FLASH_waitBusy_CallInstance;
  char FLASH_unlock_IgnoreBool;
  char FLASH_unlock_CallbackBool;
  CMOCK_FLASH_unlock_CALLBACK FLASH_unlock_CallbackFunctionPointer;
  int FLASH_unlock_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE FLASH_unlock_CallInstance;
  char FLASH_lock_IgnoreBool;
  char FLASH_lock_CallbackBool;
  CMOCK_FLASH_lock_CALLBACK FLASH_lock_CallbackFunctionPointer;
  int FLASH_lock_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE FLASH_lock_CallInstance;
  char FLASH_erasePage_IgnoreBool;
  char FLASH_erasePage_CallbackBool;
  CMOCK_FLASH_erasePage_CALLBACK FLASH_erasePage_CallbackFunctionPointer;
  int FLASH_erasePage_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE FLASH_erasePage_CallInstance;
  char FLASH_write_IgnoreBool;
  char FLASH_write_CallbackBool;
  CMOCK_FLASH_write_CALLBACK FLASH_write_CallbackFunctionPointer;
  int FLASH_write_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE FLASH_write_CallInstance;
} Mock;


void mock_bl_flash_drv_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.FLASH_waitBusy_CallInstance;
  if (Mock.FLASH_waitBusy_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FLASH_waitBusy);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.FLASH_waitBusy_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.FLASH_unlock_CallInstance;
  if (Mock.FLASH_unlock_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FLASH_unlock);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.FLASH_unlock_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.FLASH_lock_CallInstance;
  if (Mock.FLASH_lock_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FLASH_lock);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.FLASH_lock_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.FLASH_erasePage_CallInstance;
  if (Mock.FLASH_erasePage_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FLASH_erasePage);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.FLASH_erasePage_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.FLASH_write_CallInstance;
  if (Mock.FLASH_write_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FLASH_write);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.FLASH_write_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_bl_flash_drv_Init(void)
{
  mock_bl_flash_drv_Destroy();
}

void mock_bl_flash_drv_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void FLASH_waitBusy(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FLASH_waitBusy_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FLASH_waitBusy);
  cmock_call_instance = (CMOCK_FLASH_waitBusy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FLASH_waitBusy_CallInstance);
  Mock.FLASH_waitBusy_CallInstance = CMock_Guts_MemNext(Mock.FLASH_waitBusy_CallInstance);
  if (Mock.FLASH_waitBusy_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.FLASH_waitBusy_CallbackBool &&
      Mock.FLASH_waitBusy_CallbackFunctionPointer != NULL)
  {
    Mock.FLASH_waitBusy_CallbackFunctionPointer(Mock.FLASH_waitBusy_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.FLASH_waitBusy_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_FLASH_waitBusy);
    Mock.FLASH_waitBusy_CallbackFunctionPointer(Mock.FLASH_waitBusy_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void FLASH_waitBusy_CMockIgnore(void)
{
  Mock.FLASH_waitBusy_IgnoreBool = (char)1;
}

void FLASH_waitBusy_CMockStopIgnore(void)
{
  Mock.FLASH_waitBusy_IgnoreBool = (char)0;
}

void FLASH_waitBusy_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FLASH_waitBusy_CALL_INSTANCE));
  CMOCK_FLASH_waitBusy_CALL_INSTANCE* cmock_call_instance = (CMOCK_FLASH_waitBusy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FLASH_waitBusy_CallInstance = CMock_Guts_MemChain(Mock.FLASH_waitBusy_CallInstance, cmock_guts_index);
  Mock.FLASH_waitBusy_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void FLASH_waitBusy_AddCallback(CMOCK_FLASH_waitBusy_CALLBACK Callback)
{
  Mock.FLASH_waitBusy_IgnoreBool = (char)0;
  Mock.FLASH_waitBusy_CallbackBool = (char)1;
  Mock.FLASH_waitBusy_CallbackFunctionPointer = Callback;
}

void FLASH_waitBusy_Stub(CMOCK_FLASH_waitBusy_CALLBACK Callback)
{
  Mock.FLASH_waitBusy_IgnoreBool = (char)0;
  Mock.FLASH_waitBusy_CallbackBool = (char)0;
  Mock.FLASH_waitBusy_CallbackFunctionPointer = Callback;
}

void FLASH_unlock(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FLASH_unlock_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FLASH_unlock);
  cmock_call_instance = (CMOCK_FLASH_unlock_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FLASH_unlock_CallInstance);
  Mock.FLASH_unlock_CallInstance = CMock_Guts_MemNext(Mock.FLASH_unlock_CallInstance);
  if (Mock.FLASH_unlock_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.FLASH_unlock_CallbackBool &&
      Mock.FLASH_unlock_CallbackFunctionPointer != NULL)
  {
    Mock.FLASH_unlock_CallbackFunctionPointer(Mock.FLASH_unlock_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.FLASH_unlock_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_FLASH_unlock);
    Mock.FLASH_unlock_CallbackFunctionPointer(Mock.FLASH_unlock_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void FLASH_unlock_CMockIgnore(void)
{
  Mock.FLASH_unlock_IgnoreBool = (char)1;
}

void FLASH_unlock_CMockStopIgnore(void)
{
  Mock.FLASH_unlock_IgnoreBool = (char)0;
}

void FLASH_unlock_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FLASH_unlock_CALL_INSTANCE));
  CMOCK_FLASH_unlock_CALL_INSTANCE* cmock_call_instance = (CMOCK_FLASH_unlock_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FLASH_unlock_CallInstance = CMock_Guts_MemChain(Mock.FLASH_unlock_CallInstance, cmock_guts_index);
  Mock.FLASH_unlock_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void FLASH_unlock_AddCallback(CMOCK_FLASH_unlock_CALLBACK Callback)
{
  Mock.FLASH_unlock_IgnoreBool = (char)0;
  Mock.FLASH_unlock_CallbackBool = (char)1;
  Mock.FLASH_unlock_CallbackFunctionPointer = Callback;
}

void FLASH_unlock_Stub(CMOCK_FLASH_unlock_CALLBACK Callback)
{
  Mock.FLASH_unlock_IgnoreBool = (char)0;
  Mock.FLASH_unlock_CallbackBool = (char)0;
  Mock.FLASH_unlock_CallbackFunctionPointer = Callback;
}

void FLASH_lock(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FLASH_lock_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FLASH_lock);
  cmock_call_instance = (CMOCK_FLASH_lock_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FLASH_lock_CallInstance);
  Mock.FLASH_lock_CallInstance = CMock_Guts_MemNext(Mock.FLASH_lock_CallInstance);
  if (Mock.FLASH_lock_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.FLASH_lock_CallbackBool &&
      Mock.FLASH_lock_CallbackFunctionPointer != NULL)
  {
    Mock.FLASH_lock_CallbackFunctionPointer(Mock.FLASH_lock_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.FLASH_lock_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_FLASH_lock);
    Mock.FLASH_lock_CallbackFunctionPointer(Mock.FLASH_lock_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void FLASH_lock_CMockIgnore(void)
{
  Mock.FLASH_lock_IgnoreBool = (char)1;
}

void FLASH_lock_CMockStopIgnore(void)
{
  Mock.FLASH_lock_IgnoreBool = (char)0;
}

void FLASH_lock_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FLASH_lock_CALL_INSTANCE));
  CMOCK_FLASH_lock_CALL_INSTANCE* cmock_call_instance = (CMOCK_FLASH_lock_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FLASH_lock_CallInstance = CMock_Guts_MemChain(Mock.FLASH_lock_CallInstance, cmock_guts_index);
  Mock.FLASH_lock_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void FLASH_lock_AddCallback(CMOCK_FLASH_lock_CALLBACK Callback)
{
  Mock.FLASH_lock_IgnoreBool = (char)0;
  Mock.FLASH_lock_CallbackBool = (char)1;
  Mock.FLASH_lock_CallbackFunctionPointer = Callback;
}

void FLASH_lock_Stub(CMOCK_FLASH_lock_CALLBACK Callback)
{
  Mock.FLASH_lock_IgnoreBool = (char)0;
  Mock.FLASH_lock_CallbackBool = (char)0;
  Mock.FLASH_lock_CallbackFunctionPointer = Callback;
}

void FLASH_erasePage(uint32_t flash_page_no)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FLASH_erasePage_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FLASH_erasePage);
  cmock_call_instance = (CMOCK_FLASH_erasePage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FLASH_erasePage_CallInstance);
  Mock.FLASH_erasePage_CallInstance = CMock_Guts_MemNext(Mock.FLASH_erasePage_CallInstance);
  if (Mock.FLASH_erasePage_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.FLASH_erasePage_CallbackBool &&
      Mock.FLASH_erasePage_CallbackFunctionPointer != NULL)
  {
    Mock.FLASH_erasePage_CallbackFunctionPointer(flash_page_no, Mock.FLASH_erasePage_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_FLASH_erasePage,CMockString_flash_page_no);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_flash_page_no, flash_page_no, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.FLASH_erasePage_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_FLASH_erasePage);
    Mock.FLASH_erasePage_CallbackFunctionPointer(flash_page_no, Mock.FLASH_erasePage_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_FLASH_erasePage(CMOCK_FLASH_erasePage_CALL_INSTANCE* cmock_call_instance, uint32_t flash_page_no);
void CMockExpectParameters_FLASH_erasePage(CMOCK_FLASH_erasePage_CALL_INSTANCE* cmock_call_instance, uint32_t flash_page_no)
{
  cmock_call_instance->Expected_flash_page_no = flash_page_no;
}

void FLASH_erasePage_CMockIgnore(void)
{
  Mock.FLASH_erasePage_IgnoreBool = (char)1;
}

void FLASH_erasePage_CMockStopIgnore(void)
{
  Mock.FLASH_erasePage_IgnoreBool = (char)0;
}

void FLASH_erasePage_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FLASH_erasePage_CALL_INSTANCE));
  CMOCK_FLASH_erasePage_CALL_INSTANCE* cmock_call_instance = (CMOCK_FLASH_erasePage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FLASH_erasePage_CallInstance = CMock_Guts_MemChain(Mock.FLASH_erasePage_CallInstance, cmock_guts_index);
  Mock.FLASH_erasePage_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void FLASH_erasePage_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t flash_page_no)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FLASH_erasePage_CALL_INSTANCE));
  CMOCK_FLASH_erasePage_CALL_INSTANCE* cmock_call_instance = (CMOCK_FLASH_erasePage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FLASH_erasePage_CallInstance = CMock_Guts_MemChain(Mock.FLASH_erasePage_CallInstance, cmock_guts_index);
  Mock.FLASH_erasePage_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_FLASH_erasePage(cmock_call_instance, flash_page_no);
}

void FLASH_erasePage_AddCallback(CMOCK_FLASH_erasePage_CALLBACK Callback)
{
  Mock.FLASH_erasePage_IgnoreBool = (char)0;
  Mock.FLASH_erasePage_CallbackBool = (char)1;
  Mock.FLASH_erasePage_CallbackFunctionPointer = Callback;
}

void FLASH_erasePage_Stub(CMOCK_FLASH_erasePage_CALLBACK Callback)
{
  Mock.FLASH_erasePage_IgnoreBool = (char)0;
  Mock.FLASH_erasePage_CallbackBool = (char)0;
  Mock.FLASH_erasePage_CallbackFunctionPointer = Callback;
}

void FLASH_write(uint32_t addr, uint32_t const* data, size_t dataLen)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FLASH_write_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FLASH_write);
  cmock_call_instance = (CMOCK_FLASH_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FLASH_write_CallInstance);
  Mock.FLASH_write_CallInstance = CMock_Guts_MemNext(Mock.FLASH_write_CallInstance);
  if (Mock.FLASH_write_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.FLASH_write_CallbackBool &&
      Mock.FLASH_write_CallbackFunctionPointer != NULL)
  {
    Mock.FLASH_write_CallbackFunctionPointer(addr, data, dataLen, Mock.FLASH_write_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_FLASH_write,CMockString_addr);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_addr, addr, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_FLASH_write,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_data, data, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_FLASH_write,CMockString_dataLen);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_dataLen, &dataLen, sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.FLASH_write_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_FLASH_write);
    Mock.FLASH_write_CallbackFunctionPointer(addr, data, dataLen, Mock.FLASH_write_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_FLASH_write(CMOCK_FLASH_write_CALL_INSTANCE* cmock_call_instance, uint32_t addr, uint32_t const* data, size_t dataLen);
void CMockExpectParameters_FLASH_write(CMOCK_FLASH_write_CALL_INSTANCE* cmock_call_instance, uint32_t addr, uint32_t const* data, size_t dataLen)
{
  cmock_call_instance->Expected_addr = addr;
  cmock_call_instance->Expected_data = data;
  memcpy((void*)(&cmock_call_instance->Expected_dataLen), (const void*)(&dataLen),
         sizeof(size_t[sizeof(dataLen) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void FLASH_write_CMockIgnore(void)
{
  Mock.FLASH_write_IgnoreBool = (char)1;
}

void FLASH_write_CMockStopIgnore(void)
{
  Mock.FLASH_write_IgnoreBool = (char)0;
}

void FLASH_write_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FLASH_write_CALL_INSTANCE));
  CMOCK_FLASH_write_CALL_INSTANCE* cmock_call_instance = (CMOCK_FLASH_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FLASH_write_CallInstance = CMock_Guts_MemChain(Mock.FLASH_write_CallInstance, cmock_guts_index);
  Mock.FLASH_write_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void FLASH_write_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t addr, uint32_t const* data, size_t dataLen)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FLASH_write_CALL_INSTANCE));
  CMOCK_FLASH_write_CALL_INSTANCE* cmock_call_instance = (CMOCK_FLASH_write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FLASH_write_CallInstance = CMock_Guts_MemChain(Mock.FLASH_write_CallInstance, cmock_guts_index);
  Mock.FLASH_write_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_FLASH_write(cmock_call_instance, addr, data, dataLen);
}

void FLASH_write_AddCallback(CMOCK_FLASH_write_CALLBACK Callback)
{
  Mock.FLASH_write_IgnoreBool = (char)0;
  Mock.FLASH_write_CallbackBool = (char)1;
  Mock.FLASH_write_CallbackFunctionPointer = Callback;
}

void FLASH_write_Stub(CMOCK_FLASH_write_CALLBACK Callback)
{
  Mock.FLASH_write_IgnoreBool = (char)0;
  Mock.FLASH_write_CallbackBool = (char)0;
  Mock.FLASH_write_CallbackFunctionPointer = Callback;
}

