/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_BL_KEY_DRV_H
#define _MOCK_BL_KEY_DRV_H

#include "unity.h"
#include "bl_key_drv.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_bl_key_drv_Init(void);
void mock_bl_key_drv_Destroy(void);
void mock_bl_key_drv_Verify(void);




#define init_bl_key_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("init_bl_key requires _Ignore (not AndReturn)");
#define init_bl_key_Ignore() init_bl_key_CMockIgnore()
void init_bl_key_CMockIgnore(void);
#define init_bl_key_StopIgnore() init_bl_key_CMockStopIgnore()
void init_bl_key_CMockStopIgnore(void);
#define init_bl_key_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("init_bl_key requires _Expect (not AndReturn)");
#define init_bl_key_Expect() init_bl_key_CMockExpect(__LINE__)
void init_bl_key_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_init_bl_key_CALLBACK)(int cmock_num_calls);
void init_bl_key_AddCallback(CMOCK_init_bl_key_CALLBACK Callback);
void init_bl_key_Stub(CMOCK_init_bl_key_CALLBACK Callback);
#define init_bl_key_StubWithCallback init_bl_key_Stub
#define deinit_bl_key_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("deinit_bl_key requires _Ignore (not AndReturn)");
#define deinit_bl_key_Ignore() deinit_bl_key_CMockIgnore()
void deinit_bl_key_CMockIgnore(void);
#define deinit_bl_key_StopIgnore() deinit_bl_key_CMockStopIgnore()
void deinit_bl_key_CMockStopIgnore(void);
#define deinit_bl_key_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("deinit_bl_key requires _Expect (not AndReturn)");
#define deinit_bl_key_Expect() deinit_bl_key_CMockExpect(__LINE__)
void deinit_bl_key_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_deinit_bl_key_CALLBACK)(int cmock_num_calls);
void deinit_bl_key_AddCallback(CMOCK_deinit_bl_key_CALLBACK Callback);
void deinit_bl_key_Stub(CMOCK_deinit_bl_key_CALLBACK Callback);
#define deinit_bl_key_StubWithCallback deinit_bl_key_Stub
#define deinit_bl_key_clk_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("deinit_bl_key_clk requires _Ignore (not AndReturn)");
#define deinit_bl_key_clk_Ignore() deinit_bl_key_clk_CMockIgnore()
void deinit_bl_key_clk_CMockIgnore(void);
#define deinit_bl_key_clk_StopIgnore() deinit_bl_key_clk_CMockStopIgnore()
void deinit_bl_key_clk_CMockStopIgnore(void);
#define deinit_bl_key_clk_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("deinit_bl_key_clk requires _Expect (not AndReturn)");
#define deinit_bl_key_clk_Expect() deinit_bl_key_clk_CMockExpect(__LINE__)
void deinit_bl_key_clk_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_deinit_bl_key_clk_CALLBACK)(int cmock_num_calls);
void deinit_bl_key_clk_AddCallback(CMOCK_deinit_bl_key_clk_CALLBACK Callback);
void deinit_bl_key_clk_Stub(CMOCK_deinit_bl_key_clk_CALLBACK Callback);
#define deinit_bl_key_clk_StubWithCallback deinit_bl_key_clk_Stub
#define bl_key_pressed_Ignore() TEST_FAIL_MESSAGE("bl_key_pressed requires _IgnoreAndReturn");
#define bl_key_pressed_IgnoreAndReturn(cmock_retval) bl_key_pressed_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void bl_key_pressed_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define bl_key_pressed_StopIgnore() bl_key_pressed_CMockStopIgnore()
void bl_key_pressed_CMockStopIgnore(void);
#define bl_key_pressed_Expect() TEST_FAIL_MESSAGE("bl_key_pressed requires _ExpectAndReturn");
#define bl_key_pressed_ExpectAndReturn(cmock_retval) bl_key_pressed_CMockExpectAndReturn(__LINE__, cmock_retval)
void bl_key_pressed_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
typedef bool (* CMOCK_bl_key_pressed_CALLBACK)(int cmock_num_calls);
void bl_key_pressed_AddCallback(CMOCK_bl_key_pressed_CALLBACK Callback);
void bl_key_pressed_Stub(CMOCK_bl_key_pressed_CALLBACK Callback);
#define bl_key_pressed_StubWithCallback bl_key_pressed_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
