/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_bl_usart_drv.h"

static const char* CMockString_b = "b";
static const char* CMockString_byte_transmission_complete = "byte_transmission_complete";
static const char* CMockString_callback = "callback";
static const char* CMockString_d = "d";
static const char* CMockString_deinit_bl_usart_clk = "deinit_bl_usart_clk";
static const char* CMockString_deinit_bl_usart_periph = "deinit_bl_usart_periph";
static const char* CMockString_init_bl_usart = "init_bl_usart";
static const char* CMockString_l = "l";
static const char* CMockString_register_data_rx_cb = "register_data_rx_cb";
static const char* CMockString_send_byte = "send_byte";
static const char* CMockString_send_byte_table = "send_byte_table";

typedef struct _CMOCK_init_bl_usart_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_init_bl_usart_CALL_INSTANCE;

typedef struct _CMOCK_register_data_rx_cb_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  data_rx_cb_t Expected_callback;

} CMOCK_register_data_rx_cb_CALL_INSTANCE;

typedef struct _CMOCK_deinit_bl_usart_periph_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_deinit_bl_usart_periph_CALL_INSTANCE;

typedef struct _CMOCK_deinit_bl_usart_clk_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_deinit_bl_usart_clk_CALL_INSTANCE;

typedef struct _CMOCK_send_byte_table_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  const uint8_t* Expected_d;
  size_t Expected_l;

} CMOCK_send_byte_table_CALL_INSTANCE;

typedef struct _CMOCK_send_byte_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint8_t Expected_b;

} CMOCK_send_byte_CALL_INSTANCE;

typedef struct _CMOCK_byte_transmission_complete_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;

} CMOCK_byte_transmission_complete_CALL_INSTANCE;

static struct mock_bl_usart_drvInstance
{
  char init_bl_usart_IgnoreBool;
  char init_bl_usart_CallbackBool;
  CMOCK_init_bl_usart_CALLBACK init_bl_usart_CallbackFunctionPointer;
  int init_bl_usart_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE init_bl_usart_CallInstance;
  char register_data_rx_cb_IgnoreBool;
  char register_data_rx_cb_CallbackBool;
  CMOCK_register_data_rx_cb_CALLBACK register_data_rx_cb_CallbackFunctionPointer;
  int register_data_rx_cb_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE register_data_rx_cb_CallInstance;
  char deinit_bl_usart_periph_IgnoreBool;
  char deinit_bl_usart_periph_CallbackBool;
  CMOCK_deinit_bl_usart_periph_CALLBACK deinit_bl_usart_periph_CallbackFunctionPointer;
  int deinit_bl_usart_periph_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE deinit_bl_usart_periph_CallInstance;
  char deinit_bl_usart_clk_IgnoreBool;
  char deinit_bl_usart_clk_CallbackBool;
  CMOCK_deinit_bl_usart_clk_CALLBACK deinit_bl_usart_clk_CallbackFunctionPointer;
  int deinit_bl_usart_clk_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE deinit_bl_usart_clk_CallInstance;
  char send_byte_table_IgnoreBool;
  char send_byte_table_CallbackBool;
  CMOCK_send_byte_table_CALLBACK send_byte_table_CallbackFunctionPointer;
  int send_byte_table_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE send_byte_table_CallInstance;
  char send_byte_IgnoreBool;
  char send_byte_CallbackBool;
  CMOCK_send_byte_CALLBACK send_byte_CallbackFunctionPointer;
  int send_byte_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE send_byte_CallInstance;
  char byte_transmission_complete_IgnoreBool;
  bool byte_transmission_complete_FinalReturn;
  char byte_transmission_complete_CallbackBool;
  CMOCK_byte_transmission_complete_CALLBACK byte_transmission_complete_CallbackFunctionPointer;
  int byte_transmission_complete_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE byte_transmission_complete_CallInstance;
} Mock;


void mock_bl_usart_drv_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.init_bl_usart_CallInstance;
  if (Mock.init_bl_usart_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_init_bl_usart);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.init_bl_usart_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.register_data_rx_cb_CallInstance;
  if (Mock.register_data_rx_cb_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_register_data_rx_cb);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.register_data_rx_cb_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.deinit_bl_usart_periph_CallInstance;
  if (Mock.deinit_bl_usart_periph_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_deinit_bl_usart_periph);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.deinit_bl_usart_periph_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.deinit_bl_usart_clk_CallInstance;
  if (Mock.deinit_bl_usart_clk_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_deinit_bl_usart_clk);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.deinit_bl_usart_clk_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.send_byte_table_CallInstance;
  if (Mock.send_byte_table_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_send_byte_table);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.send_byte_table_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.send_byte_CallInstance;
  if (Mock.send_byte_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_send_byte);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.send_byte_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.byte_transmission_complete_CallInstance;
  if (Mock.byte_transmission_complete_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_byte_transmission_complete);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.byte_transmission_complete_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_bl_usart_drv_Init(void)
{
  mock_bl_usart_drv_Destroy();
}

void mock_bl_usart_drv_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void init_bl_usart(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_init_bl_usart_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_init_bl_usart);
  cmock_call_instance = (CMOCK_init_bl_usart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.init_bl_usart_CallInstance);
  Mock.init_bl_usart_CallInstance = CMock_Guts_MemNext(Mock.init_bl_usart_CallInstance);
  if (Mock.init_bl_usart_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.init_bl_usart_CallbackBool &&
      Mock.init_bl_usart_CallbackFunctionPointer != NULL)
  {
    Mock.init_bl_usart_CallbackFunctionPointer(Mock.init_bl_usart_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.init_bl_usart_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_init_bl_usart);
    Mock.init_bl_usart_CallbackFunctionPointer(Mock.init_bl_usart_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void init_bl_usart_CMockIgnore(void)
{
  Mock.init_bl_usart_IgnoreBool = (char)1;
}

void init_bl_usart_CMockStopIgnore(void)
{
  Mock.init_bl_usart_IgnoreBool = (char)0;
}

void init_bl_usart_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_init_bl_usart_CALL_INSTANCE));
  CMOCK_init_bl_usart_CALL_INSTANCE* cmock_call_instance = (CMOCK_init_bl_usart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.init_bl_usart_CallInstance = CMock_Guts_MemChain(Mock.init_bl_usart_CallInstance, cmock_guts_index);
  Mock.init_bl_usart_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void init_bl_usart_AddCallback(CMOCK_init_bl_usart_CALLBACK Callback)
{
  Mock.init_bl_usart_IgnoreBool = (char)0;
  Mock.init_bl_usart_CallbackBool = (char)1;
  Mock.init_bl_usart_CallbackFunctionPointer = Callback;
}

void init_bl_usart_Stub(CMOCK_init_bl_usart_CALLBACK Callback)
{
  Mock.init_bl_usart_IgnoreBool = (char)0;
  Mock.init_bl_usart_CallbackBool = (char)0;
  Mock.init_bl_usart_CallbackFunctionPointer = Callback;
}

void register_data_rx_cb(data_rx_cb_t callback)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_register_data_rx_cb_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_register_data_rx_cb);
  cmock_call_instance = (CMOCK_register_data_rx_cb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.register_data_rx_cb_CallInstance);
  Mock.register_data_rx_cb_CallInstance = CMock_Guts_MemNext(Mock.register_data_rx_cb_CallInstance);
  if (Mock.register_data_rx_cb_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.register_data_rx_cb_CallbackBool &&
      Mock.register_data_rx_cb_CallbackFunctionPointer != NULL)
  {
    Mock.register_data_rx_cb_CallbackFunctionPointer(callback, Mock.register_data_rx_cb_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_register_data_rx_cb,CMockString_callback);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_callback, &callback, sizeof(data_rx_cb_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.register_data_rx_cb_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_register_data_rx_cb);
    Mock.register_data_rx_cb_CallbackFunctionPointer(callback, Mock.register_data_rx_cb_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_register_data_rx_cb(CMOCK_register_data_rx_cb_CALL_INSTANCE* cmock_call_instance, data_rx_cb_t callback);
void CMockExpectParameters_register_data_rx_cb(CMOCK_register_data_rx_cb_CALL_INSTANCE* cmock_call_instance, data_rx_cb_t callback)
{
  memcpy((void*)(&cmock_call_instance->Expected_callback), (const void*)(&callback),
         sizeof(data_rx_cb_t[sizeof(callback) == sizeof(data_rx_cb_t) ? 1 : -1])); /* add data_rx_cb_t to :treat_as_array if this causes an error */
}

void register_data_rx_cb_CMockIgnore(void)
{
  Mock.register_data_rx_cb_IgnoreBool = (char)1;
}

void register_data_rx_cb_CMockStopIgnore(void)
{
  Mock.register_data_rx_cb_IgnoreBool = (char)0;
}

void register_data_rx_cb_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_register_data_rx_cb_CALL_INSTANCE));
  CMOCK_register_data_rx_cb_CALL_INSTANCE* cmock_call_instance = (CMOCK_register_data_rx_cb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.register_data_rx_cb_CallInstance = CMock_Guts_MemChain(Mock.register_data_rx_cb_CallInstance, cmock_guts_index);
  Mock.register_data_rx_cb_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void register_data_rx_cb_CMockExpect(UNITY_LINE_TYPE cmock_line, data_rx_cb_t callback)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_register_data_rx_cb_CALL_INSTANCE));
  CMOCK_register_data_rx_cb_CALL_INSTANCE* cmock_call_instance = (CMOCK_register_data_rx_cb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.register_data_rx_cb_CallInstance = CMock_Guts_MemChain(Mock.register_data_rx_cb_CallInstance, cmock_guts_index);
  Mock.register_data_rx_cb_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_register_data_rx_cb(cmock_call_instance, callback);
}

void register_data_rx_cb_AddCallback(CMOCK_register_data_rx_cb_CALLBACK Callback)
{
  Mock.register_data_rx_cb_IgnoreBool = (char)0;
  Mock.register_data_rx_cb_CallbackBool = (char)1;
  Mock.register_data_rx_cb_CallbackFunctionPointer = Callback;
}

void register_data_rx_cb_Stub(CMOCK_register_data_rx_cb_CALLBACK Callback)
{
  Mock.register_data_rx_cb_IgnoreBool = (char)0;
  Mock.register_data_rx_cb_CallbackBool = (char)0;
  Mock.register_data_rx_cb_CallbackFunctionPointer = Callback;
}

void deinit_bl_usart_periph(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_deinit_bl_usart_periph_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_deinit_bl_usart_periph);
  cmock_call_instance = (CMOCK_deinit_bl_usart_periph_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.deinit_bl_usart_periph_CallInstance);
  Mock.deinit_bl_usart_periph_CallInstance = CMock_Guts_MemNext(Mock.deinit_bl_usart_periph_CallInstance);
  if (Mock.deinit_bl_usart_periph_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.deinit_bl_usart_periph_CallbackBool &&
      Mock.deinit_bl_usart_periph_CallbackFunctionPointer != NULL)
  {
    Mock.deinit_bl_usart_periph_CallbackFunctionPointer(Mock.deinit_bl_usart_periph_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.deinit_bl_usart_periph_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_deinit_bl_usart_periph);
    Mock.deinit_bl_usart_periph_CallbackFunctionPointer(Mock.deinit_bl_usart_periph_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void deinit_bl_usart_periph_CMockIgnore(void)
{
  Mock.deinit_bl_usart_periph_IgnoreBool = (char)1;
}

void deinit_bl_usart_periph_CMockStopIgnore(void)
{
  Mock.deinit_bl_usart_periph_IgnoreBool = (char)0;
}

void deinit_bl_usart_periph_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_deinit_bl_usart_periph_CALL_INSTANCE));
  CMOCK_deinit_bl_usart_periph_CALL_INSTANCE* cmock_call_instance = (CMOCK_deinit_bl_usart_periph_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.deinit_bl_usart_periph_CallInstance = CMock_Guts_MemChain(Mock.deinit_bl_usart_periph_CallInstance, cmock_guts_index);
  Mock.deinit_bl_usart_periph_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void deinit_bl_usart_periph_AddCallback(CMOCK_deinit_bl_usart_periph_CALLBACK Callback)
{
  Mock.deinit_bl_usart_periph_IgnoreBool = (char)0;
  Mock.deinit_bl_usart_periph_CallbackBool = (char)1;
  Mock.deinit_bl_usart_periph_CallbackFunctionPointer = Callback;
}

void deinit_bl_usart_periph_Stub(CMOCK_deinit_bl_usart_periph_CALLBACK Callback)
{
  Mock.deinit_bl_usart_periph_IgnoreBool = (char)0;
  Mock.deinit_bl_usart_periph_CallbackBool = (char)0;
  Mock.deinit_bl_usart_periph_CallbackFunctionPointer = Callback;
}

void deinit_bl_usart_clk(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_deinit_bl_usart_clk_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_deinit_bl_usart_clk);
  cmock_call_instance = (CMOCK_deinit_bl_usart_clk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.deinit_bl_usart_clk_CallInstance);
  Mock.deinit_bl_usart_clk_CallInstance = CMock_Guts_MemNext(Mock.deinit_bl_usart_clk_CallInstance);
  if (Mock.deinit_bl_usart_clk_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.deinit_bl_usart_clk_CallbackBool &&
      Mock.deinit_bl_usart_clk_CallbackFunctionPointer != NULL)
  {
    Mock.deinit_bl_usart_clk_CallbackFunctionPointer(Mock.deinit_bl_usart_clk_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.deinit_bl_usart_clk_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_deinit_bl_usart_clk);
    Mock.deinit_bl_usart_clk_CallbackFunctionPointer(Mock.deinit_bl_usart_clk_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void deinit_bl_usart_clk_CMockIgnore(void)
{
  Mock.deinit_bl_usart_clk_IgnoreBool = (char)1;
}

void deinit_bl_usart_clk_CMockStopIgnore(void)
{
  Mock.deinit_bl_usart_clk_IgnoreBool = (char)0;
}

void deinit_bl_usart_clk_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_deinit_bl_usart_clk_CALL_INSTANCE));
  CMOCK_deinit_bl_usart_clk_CALL_INSTANCE* cmock_call_instance = (CMOCK_deinit_bl_usart_clk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.deinit_bl_usart_clk_CallInstance = CMock_Guts_MemChain(Mock.deinit_bl_usart_clk_CallInstance, cmock_guts_index);
  Mock.deinit_bl_usart_clk_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void deinit_bl_usart_clk_AddCallback(CMOCK_deinit_bl_usart_clk_CALLBACK Callback)
{
  Mock.deinit_bl_usart_clk_IgnoreBool = (char)0;
  Mock.deinit_bl_usart_clk_CallbackBool = (char)1;
  Mock.deinit_bl_usart_clk_CallbackFunctionPointer = Callback;
}

void deinit_bl_usart_clk_Stub(CMOCK_deinit_bl_usart_clk_CALLBACK Callback)
{
  Mock.deinit_bl_usart_clk_IgnoreBool = (char)0;
  Mock.deinit_bl_usart_clk_CallbackBool = (char)0;
  Mock.deinit_bl_usart_clk_CallbackFunctionPointer = Callback;
}

void send_byte_table(const uint8_t* d, size_t l)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_send_byte_table_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_send_byte_table);
  cmock_call_instance = (CMOCK_send_byte_table_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.send_byte_table_CallInstance);
  Mock.send_byte_table_CallInstance = CMock_Guts_MemNext(Mock.send_byte_table_CallInstance);
  if (Mock.send_byte_table_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.send_byte_table_CallbackBool &&
      Mock.send_byte_table_CallbackFunctionPointer != NULL)
  {
    Mock.send_byte_table_CallbackFunctionPointer(d, l, Mock.send_byte_table_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_send_byte_table,CMockString_d);
    if (cmock_call_instance->Expected_d == NULL)
      { UNITY_TEST_ASSERT_NULL(d, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_d, d, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_send_byte_table,CMockString_l);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_l, &l, sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.send_byte_table_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_send_byte_table);
    Mock.send_byte_table_CallbackFunctionPointer(d, l, Mock.send_byte_table_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_send_byte_table(CMOCK_send_byte_table_CALL_INSTANCE* cmock_call_instance, const uint8_t* d, size_t l);
void CMockExpectParameters_send_byte_table(CMOCK_send_byte_table_CALL_INSTANCE* cmock_call_instance, const uint8_t* d, size_t l)
{
  cmock_call_instance->Expected_d = d;
  memcpy((void*)(&cmock_call_instance->Expected_l), (const void*)(&l),
         sizeof(size_t[sizeof(l) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void send_byte_table_CMockIgnore(void)
{
  Mock.send_byte_table_IgnoreBool = (char)1;
}

void send_byte_table_CMockStopIgnore(void)
{
  Mock.send_byte_table_IgnoreBool = (char)0;
}

void send_byte_table_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_send_byte_table_CALL_INSTANCE));
  CMOCK_send_byte_table_CALL_INSTANCE* cmock_call_instance = (CMOCK_send_byte_table_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.send_byte_table_CallInstance = CMock_Guts_MemChain(Mock.send_byte_table_CallInstance, cmock_guts_index);
  Mock.send_byte_table_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void send_byte_table_CMockExpect(UNITY_LINE_TYPE cmock_line, const uint8_t* d, size_t l)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_send_byte_table_CALL_INSTANCE));
  CMOCK_send_byte_table_CALL_INSTANCE* cmock_call_instance = (CMOCK_send_byte_table_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.send_byte_table_CallInstance = CMock_Guts_MemChain(Mock.send_byte_table_CallInstance, cmock_guts_index);
  Mock.send_byte_table_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_send_byte_table(cmock_call_instance, d, l);
}

void send_byte_table_AddCallback(CMOCK_send_byte_table_CALLBACK Callback)
{
  Mock.send_byte_table_IgnoreBool = (char)0;
  Mock.send_byte_table_CallbackBool = (char)1;
  Mock.send_byte_table_CallbackFunctionPointer = Callback;
}

void send_byte_table_Stub(CMOCK_send_byte_table_CALLBACK Callback)
{
  Mock.send_byte_table_IgnoreBool = (char)0;
  Mock.send_byte_table_CallbackBool = (char)0;
  Mock.send_byte_table_CallbackFunctionPointer = Callback;
}

void send_byte(uint8_t b)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_send_byte_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_send_byte);
  cmock_call_instance = (CMOCK_send_byte_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.send_byte_CallInstance);
  Mock.send_byte_CallInstance = CMock_Guts_MemNext(Mock.send_byte_CallInstance);
  if (Mock.send_byte_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.send_byte_CallbackBool &&
      Mock.send_byte_CallbackFunctionPointer != NULL)
  {
    Mock.send_byte_CallbackFunctionPointer(b, Mock.send_byte_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_send_byte,CMockString_b);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_b, b, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.send_byte_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_send_byte);
    Mock.send_byte_CallbackFunctionPointer(b, Mock.send_byte_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_send_byte(CMOCK_send_byte_CALL_INSTANCE* cmock_call_instance, uint8_t b);
void CMockExpectParameters_send_byte(CMOCK_send_byte_CALL_INSTANCE* cmock_call_instance, uint8_t b)
{
  cmock_call_instance->Expected_b = b;
}

void send_byte_CMockIgnore(void)
{
  Mock.send_byte_IgnoreBool = (char)1;
}

void send_byte_CMockStopIgnore(void)
{
  Mock.send_byte_IgnoreBool = (char)0;
}

void send_byte_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_send_byte_CALL_INSTANCE));
  CMOCK_send_byte_CALL_INSTANCE* cmock_call_instance = (CMOCK_send_byte_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.send_byte_CallInstance = CMock_Guts_MemChain(Mock.send_byte_CallInstance, cmock_guts_index);
  Mock.send_byte_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void send_byte_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t b)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_send_byte_CALL_INSTANCE));
  CMOCK_send_byte_CALL_INSTANCE* cmock_call_instance = (CMOCK_send_byte_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.send_byte_CallInstance = CMock_Guts_MemChain(Mock.send_byte_CallInstance, cmock_guts_index);
  Mock.send_byte_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_send_byte(cmock_call_instance, b);
}

void send_byte_AddCallback(CMOCK_send_byte_CALLBACK Callback)
{
  Mock.send_byte_IgnoreBool = (char)0;
  Mock.send_byte_CallbackBool = (char)1;
  Mock.send_byte_CallbackFunctionPointer = Callback;
}

void send_byte_Stub(CMOCK_send_byte_CALLBACK Callback)
{
  Mock.send_byte_IgnoreBool = (char)0;
  Mock.send_byte_CallbackBool = (char)0;
  Mock.send_byte_CallbackFunctionPointer = Callback;
}

bool byte_transmission_complete(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_byte_transmission_complete_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_byte_transmission_complete);
  cmock_call_instance = (CMOCK_byte_transmission_complete_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.byte_transmission_complete_CallInstance);
  Mock.byte_transmission_complete_CallInstance = CMock_Guts_MemNext(Mock.byte_transmission_complete_CallInstance);
  if (Mock.byte_transmission_complete_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.byte_transmission_complete_FinalReturn;
    Mock.byte_transmission_complete_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.byte_transmission_complete_CallbackBool &&
      Mock.byte_transmission_complete_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.byte_transmission_complete_CallbackFunctionPointer(Mock.byte_transmission_complete_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.byte_transmission_complete_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_byte_transmission_complete);
    cmock_call_instance->ReturnVal = Mock.byte_transmission_complete_CallbackFunctionPointer(Mock.byte_transmission_complete_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void byte_transmission_complete_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_byte_transmission_complete_CALL_INSTANCE));
  CMOCK_byte_transmission_complete_CALL_INSTANCE* cmock_call_instance = (CMOCK_byte_transmission_complete_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.byte_transmission_complete_CallInstance = CMock_Guts_MemChain(Mock.byte_transmission_complete_CallInstance, cmock_guts_index);
  Mock.byte_transmission_complete_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.byte_transmission_complete_IgnoreBool = (char)1;
}

void byte_transmission_complete_CMockStopIgnore(void)
{
  if(Mock.byte_transmission_complete_IgnoreBool)
    Mock.byte_transmission_complete_CallInstance = CMock_Guts_MemNext(Mock.byte_transmission_complete_CallInstance);
  Mock.byte_transmission_complete_IgnoreBool = (char)0;
}

void byte_transmission_complete_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_byte_transmission_complete_CALL_INSTANCE));
  CMOCK_byte_transmission_complete_CALL_INSTANCE* cmock_call_instance = (CMOCK_byte_transmission_complete_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.byte_transmission_complete_CallInstance = CMock_Guts_MemChain(Mock.byte_transmission_complete_CallInstance, cmock_guts_index);
  Mock.byte_transmission_complete_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void byte_transmission_complete_AddCallback(CMOCK_byte_transmission_complete_CALLBACK Callback)
{
  Mock.byte_transmission_complete_IgnoreBool = (char)0;
  Mock.byte_transmission_complete_CallbackBool = (char)1;
  Mock.byte_transmission_complete_CallbackFunctionPointer = Callback;
}

void byte_transmission_complete_Stub(CMOCK_byte_transmission_complete_CALLBACK Callback)
{
  Mock.byte_transmission_complete_IgnoreBool = (char)0;
  Mock.byte_transmission_complete_CallbackBool = (char)0;
  Mock.byte_transmission_complete_CallbackFunctionPointer = Callback;
}

