/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_CRC_API_H
#define _MOCK_CRC_API_H

#include "unity.h"
#include "crc_api.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_crc_api_Init(void);
void mock_crc_api_Destroy(void);
void mock_crc_api_Verify(void);




#define CRC_hw_init_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("CRC_hw_init requires _Ignore (not AndReturn)");
#define CRC_hw_init_Ignore() CRC_hw_init_CMockIgnore()
void CRC_hw_init_CMockIgnore(void);
#define CRC_hw_init_StopIgnore() CRC_hw_init_CMockStopIgnore()
void CRC_hw_init_CMockStopIgnore(void);
#define CRC_hw_init_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("CRC_hw_init requires _Expect (not AndReturn)");
#define CRC_hw_init_Expect() CRC_hw_init_CMockExpect(__LINE__)
void CRC_hw_init_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_CRC_hw_init_CALLBACK)(int cmock_num_calls);
void CRC_hw_init_AddCallback(CMOCK_CRC_hw_init_CALLBACK Callback);
void CRC_hw_init_Stub(CMOCK_CRC_hw_init_CALLBACK Callback);
#define CRC_hw_init_StubWithCallback CRC_hw_init_Stub
#define CRC_init_Ignore() TEST_FAIL_MESSAGE("CRC_init requires _IgnoreAndReturn");
#define CRC_init_IgnoreAndReturn(cmock_retval) CRC_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void CRC_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define CRC_init_StopIgnore() CRC_init_CMockStopIgnore()
void CRC_init_CMockStopIgnore(void);
#define CRC_init_Expect() TEST_FAIL_MESSAGE("CRC_init requires _ExpectAndReturn");
#define CRC_init_ExpectAndReturn(cmock_retval) CRC_init_CMockExpectAndReturn(__LINE__, cmock_retval)
void CRC_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_CRC_init_CALLBACK)(int cmock_num_calls);
void CRC_init_AddCallback(CMOCK_CRC_init_CALLBACK Callback);
void CRC_init_Stub(CMOCK_CRC_init_CALLBACK Callback);
#define CRC_init_StubWithCallback CRC_init_Stub
#define CRC_add_byte_Ignore() TEST_FAIL_MESSAGE("CRC_add_byte requires _IgnoreAndReturn");
#define CRC_add_byte_IgnoreAndReturn(cmock_retval) CRC_add_byte_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void CRC_add_byte_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define CRC_add_byte_StopIgnore() CRC_add_byte_CMockStopIgnore()
void CRC_add_byte_CMockStopIgnore(void);
#define CRC_add_byte_ExpectAnyArgs() TEST_FAIL_MESSAGE("CRC_add_byte requires _ExpectAnyArgsAndReturn");
#define CRC_add_byte_ExpectAnyArgsAndReturn(cmock_retval) CRC_add_byte_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void CRC_add_byte_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define CRC_add_byte_Expect(crc, b) TEST_FAIL_MESSAGE("CRC_add_byte requires _ExpectAndReturn");
#define CRC_add_byte_ExpectAndReturn(crc, b, cmock_retval) CRC_add_byte_CMockExpectAndReturn(__LINE__, crc, b, cmock_retval)
void CRC_add_byte_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t crc, uint8_t b, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_CRC_add_byte_CALLBACK)(uint32_t crc, uint8_t b, int cmock_num_calls);
void CRC_add_byte_AddCallback(CMOCK_CRC_add_byte_CALLBACK Callback);
void CRC_add_byte_Stub(CMOCK_CRC_add_byte_CALLBACK Callback);
#define CRC_add_byte_StubWithCallback CRC_add_byte_Stub
#define CRC_add_byte_tab_Ignore() TEST_FAIL_MESSAGE("CRC_add_byte_tab requires _IgnoreAndReturn");
#define CRC_add_byte_tab_IgnoreAndReturn(cmock_retval) CRC_add_byte_tab_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void CRC_add_byte_tab_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define CRC_add_byte_tab_StopIgnore() CRC_add_byte_tab_CMockStopIgnore()
void CRC_add_byte_tab_CMockStopIgnore(void);
#define CRC_add_byte_tab_ExpectAnyArgs() TEST_FAIL_MESSAGE("CRC_add_byte_tab requires _ExpectAnyArgsAndReturn");
#define CRC_add_byte_tab_ExpectAnyArgsAndReturn(cmock_retval) CRC_add_byte_tab_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void CRC_add_byte_tab_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define CRC_add_byte_tab_Expect(crc, data, dataLen) TEST_FAIL_MESSAGE("CRC_add_byte_tab requires _ExpectAndReturn");
#define CRC_add_byte_tab_ExpectAndReturn(crc, data, dataLen, cmock_retval) CRC_add_byte_tab_CMockExpectAndReturn(__LINE__, crc, data, dataLen, cmock_retval)
void CRC_add_byte_tab_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t crc, uint8_t const* data, size_t dataLen, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_CRC_add_byte_tab_CALLBACK)(uint32_t crc, uint8_t const* data, size_t dataLen, int cmock_num_calls);
void CRC_add_byte_tab_AddCallback(CMOCK_CRC_add_byte_tab_CALLBACK Callback);
void CRC_add_byte_tab_Stub(CMOCK_CRC_add_byte_tab_CALLBACK Callback);
#define CRC_add_byte_tab_StubWithCallback CRC_add_byte_tab_Stub
#define CRC_result_Ignore() TEST_FAIL_MESSAGE("CRC_result requires _IgnoreAndReturn");
#define CRC_result_IgnoreAndReturn(cmock_retval) CRC_result_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void CRC_result_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define CRC_result_StopIgnore() CRC_result_CMockStopIgnore()
void CRC_result_CMockStopIgnore(void);
#define CRC_result_ExpectAnyArgs() TEST_FAIL_MESSAGE("CRC_result requires _ExpectAnyArgsAndReturn");
#define CRC_result_ExpectAnyArgsAndReturn(cmock_retval) CRC_result_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void CRC_result_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define CRC_result_Expect(crc) TEST_FAIL_MESSAGE("CRC_result requires _ExpectAndReturn");
#define CRC_result_ExpectAndReturn(crc, cmock_retval) CRC_result_CMockExpectAndReturn(__LINE__, crc, cmock_retval)
void CRC_result_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t crc, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_CRC_result_CALLBACK)(uint32_t crc, int cmock_num_calls);
void CRC_result_AddCallback(CMOCK_CRC_result_CALLBACK Callback);
void CRC_result_Stub(CMOCK_CRC_result_CALLBACK Callback);
#define CRC_result_StubWithCallback CRC_result_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
