/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_AES_H
#define _MOCK_AES_H

#include "unity.h"
#include "aes.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_aes_Init(void);
void mock_aes_Destroy(void);
void mock_aes_Verify(void);




#define AES_CBC_init_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("AES_CBC_init requires _Ignore (not AndReturn)");
#define AES_CBC_init_Ignore() AES_CBC_init_CMockIgnore()
void AES_CBC_init_CMockIgnore(void);
#define AES_CBC_init_StopIgnore() AES_CBC_init_CMockStopIgnore()
void AES_CBC_init_CMockStopIgnore(void);
#define AES_CBC_init_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("AES_CBC_init requires _ExpectAnyArgs (not AndReturn)");
#define AES_CBC_init_ExpectAnyArgs() AES_CBC_init_CMockExpectAnyArgs(__LINE__)
void AES_CBC_init_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define AES_CBC_init_ExpectAndReturn(key, iv, cmock_retval) TEST_FAIL_MESSAGE("AES_CBC_init requires _Expect (not AndReturn)");
#define AES_CBC_init_Expect(key, iv) AES_CBC_init_CMockExpect(__LINE__, key, iv)
void AES_CBC_init_CMockExpect(UNITY_LINE_TYPE cmock_line, const uint8_t* key, const uint8_t* iv);
typedef void (* CMOCK_AES_CBC_init_CALLBACK)(const uint8_t* key, const uint8_t* iv, int cmock_num_calls);
void AES_CBC_init_AddCallback(CMOCK_AES_CBC_init_CALLBACK Callback);
void AES_CBC_init_Stub(CMOCK_AES_CBC_init_CALLBACK Callback);
#define AES_CBC_init_StubWithCallback AES_CBC_init_Stub
#define AES_CBC_decrypt_buffer_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("AES_CBC_decrypt_buffer requires _Ignore (not AndReturn)");
#define AES_CBC_decrypt_buffer_Ignore() AES_CBC_decrypt_buffer_CMockIgnore()
void AES_CBC_decrypt_buffer_CMockIgnore(void);
#define AES_CBC_decrypt_buffer_StopIgnore() AES_CBC_decrypt_buffer_CMockStopIgnore()
void AES_CBC_decrypt_buffer_CMockStopIgnore(void);
#define AES_CBC_decrypt_buffer_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("AES_CBC_decrypt_buffer requires _ExpectAnyArgs (not AndReturn)");
#define AES_CBC_decrypt_buffer_ExpectAnyArgs() AES_CBC_decrypt_buffer_CMockExpectAnyArgs(__LINE__)
void AES_CBC_decrypt_buffer_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define AES_CBC_decrypt_buffer_ExpectAndReturn(buf, length, cmock_retval) TEST_FAIL_MESSAGE("AES_CBC_decrypt_buffer requires _Expect (not AndReturn)");
#define AES_CBC_decrypt_buffer_Expect(buf, length) AES_CBC_decrypt_buffer_CMockExpect(__LINE__, buf, length)
void AES_CBC_decrypt_buffer_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t* buf, uint32_t length);
typedef void (* CMOCK_AES_CBC_decrypt_buffer_CALLBACK)(uint8_t* buf, uint32_t length, int cmock_num_calls);
void AES_CBC_decrypt_buffer_AddCallback(CMOCK_AES_CBC_decrypt_buffer_CALLBACK Callback);
void AES_CBC_decrypt_buffer_Stub(CMOCK_AES_CBC_decrypt_buffer_CALLBACK Callback);
#define AES_CBC_decrypt_buffer_StubWithCallback AES_CBC_decrypt_buffer_Stub
#define AES_CBC_decrypt_buffer_ReturnThruPtr_buf(buf) AES_CBC_decrypt_buffer_CMockReturnMemThruPtr_buf(__LINE__, buf, sizeof(uint8_t))
#define AES_CBC_decrypt_buffer_ReturnArrayThruPtr_buf(buf, cmock_len) AES_CBC_decrypt_buffer_CMockReturnMemThruPtr_buf(__LINE__, buf, (cmock_len * sizeof(*buf)))
#define AES_CBC_decrypt_buffer_ReturnMemThruPtr_buf(buf, cmock_size) AES_CBC_decrypt_buffer_CMockReturnMemThruPtr_buf(__LINE__, buf, (cmock_size))
void AES_CBC_decrypt_buffer_CMockReturnMemThruPtr_buf(UNITY_LINE_TYPE cmock_line, uint8_t const* buf, size_t cmock_size);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
