/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_CORE_DRV_H
#define _MOCK_CORE_DRV_H

#include "unity.h"
#include "core_drv.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_core_drv_Init(void);
void mock_core_drv_Destroy(void);
void mock_core_drv_Verify(void);




#define init_sys_tick_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("init_sys_tick requires _Ignore (not AndReturn)");
#define init_sys_tick_Ignore() init_sys_tick_CMockIgnore()
void init_sys_tick_CMockIgnore(void);
#define init_sys_tick_StopIgnore() init_sys_tick_CMockStopIgnore()
void init_sys_tick_CMockStopIgnore(void);
#define init_sys_tick_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("init_sys_tick requires _Expect (not AndReturn)");
#define init_sys_tick_Expect() init_sys_tick_CMockExpect(__LINE__)
void init_sys_tick_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_init_sys_tick_CALLBACK)(int cmock_num_calls);
void init_sys_tick_AddCallback(CMOCK_init_sys_tick_CALLBACK Callback);
void init_sys_tick_Stub(CMOCK_init_sys_tick_CALLBACK Callback);
#define init_sys_tick_StubWithCallback init_sys_tick_Stub
#define deinit_sys_tick_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("deinit_sys_tick requires _Ignore (not AndReturn)");
#define deinit_sys_tick_Ignore() deinit_sys_tick_CMockIgnore()
void deinit_sys_tick_CMockIgnore(void);
#define deinit_sys_tick_StopIgnore() deinit_sys_tick_CMockStopIgnore()
void deinit_sys_tick_CMockStopIgnore(void);
#define deinit_sys_tick_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("deinit_sys_tick requires _Expect (not AndReturn)");
#define deinit_sys_tick_Expect() deinit_sys_tick_CMockExpect(__LINE__)
void deinit_sys_tick_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_deinit_sys_tick_CALLBACK)(int cmock_num_calls);
void deinit_sys_tick_AddCallback(CMOCK_deinit_sys_tick_CALLBACK Callback);
void deinit_sys_tick_Stub(CMOCK_deinit_sys_tick_CALLBACK Callback);
#define deinit_sys_tick_StubWithCallback deinit_sys_tick_Stub
#define deinit_nvic_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("deinit_nvic requires _Ignore (not AndReturn)");
#define deinit_nvic_Ignore() deinit_nvic_CMockIgnore()
void deinit_nvic_CMockIgnore(void);
#define deinit_nvic_StopIgnore() deinit_nvic_CMockStopIgnore()
void deinit_nvic_CMockStopIgnore(void);
#define deinit_nvic_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("deinit_nvic requires _Expect (not AndReturn)");
#define deinit_nvic_Expect() deinit_nvic_CMockExpect(__LINE__)
void deinit_nvic_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_deinit_nvic_CALLBACK)(int cmock_num_calls);
void deinit_nvic_AddCallback(CMOCK_deinit_nvic_CALLBACK Callback);
void deinit_nvic_Stub(CMOCK_deinit_nvic_CALLBACK Callback);
#define deinit_nvic_StubWithCallback deinit_nvic_Stub
#define register_sysTick_cb_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("register_sysTick_cb requires _Ignore (not AndReturn)");
#define register_sysTick_cb_Ignore() register_sysTick_cb_CMockIgnore()
void register_sysTick_cb_CMockIgnore(void);
#define register_sysTick_cb_StopIgnore() register_sysTick_cb_CMockStopIgnore()
void register_sysTick_cb_CMockStopIgnore(void);
#define register_sysTick_cb_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("register_sysTick_cb requires _ExpectAnyArgs (not AndReturn)");
#define register_sysTick_cb_ExpectAnyArgs() register_sysTick_cb_CMockExpectAnyArgs(__LINE__)
void register_sysTick_cb_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define register_sysTick_cb_ExpectAndReturn(callback, cmock_retval) TEST_FAIL_MESSAGE("register_sysTick_cb requires _Expect (not AndReturn)");
#define register_sysTick_cb_Expect(callback) register_sysTick_cb_CMockExpect(__LINE__, callback)
void register_sysTick_cb_CMockExpect(UNITY_LINE_TYPE cmock_line, SysTick_cb_t callback);
typedef void (* CMOCK_register_sysTick_cb_CALLBACK)(SysTick_cb_t callback, int cmock_num_calls);
void register_sysTick_cb_AddCallback(CMOCK_register_sysTick_cb_CALLBACK Callback);
void register_sysTick_cb_Stub(CMOCK_register_sysTick_cb_CALLBACK Callback);
#define register_sysTick_cb_StubWithCallback register_sysTick_cb_Stub
#define jump_to_app_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("jump_to_app requires _Ignore (not AndReturn)");
#define jump_to_app_Ignore() jump_to_app_CMockIgnore()
void jump_to_app_CMockIgnore(void);
#define jump_to_app_StopIgnore() jump_to_app_CMockStopIgnore()
void jump_to_app_CMockStopIgnore(void);
#define jump_to_app_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("jump_to_app requires _Expect (not AndReturn)");
#define jump_to_app_Expect() jump_to_app_CMockExpect(__LINE__)
void jump_to_app_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_jump_to_app_CALLBACK)(int cmock_num_calls);
void jump_to_app_AddCallback(CMOCK_jump_to_app_CALLBACK Callback);
void jump_to_app_Stub(CMOCK_jump_to_app_CALLBACK Callback);
#define jump_to_app_StubWithCallback jump_to_app_Stub
#define system_reset_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("system_reset requires _Ignore (not AndReturn)");
#define system_reset_Ignore() system_reset_CMockIgnore()
void system_reset_CMockIgnore(void);
#define system_reset_StopIgnore() system_reset_CMockStopIgnore()
void system_reset_CMockStopIgnore(void);
#define system_reset_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("system_reset requires _Expect (not AndReturn)");
#define system_reset_Expect() system_reset_CMockExpect(__LINE__)
void system_reset_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_system_reset_CALLBACK)(int cmock_num_calls);
void system_reset_AddCallback(CMOCK_system_reset_CALLBACK Callback);
void system_reset_Stub(CMOCK_system_reset_CALLBACK Callback);
#define system_reset_StubWithCallback system_reset_Stub
#define CORE_is_valid_app_Ignore() TEST_FAIL_MESSAGE("CORE_is_valid_app requires _IgnoreAndReturn");
#define CORE_is_valid_app_IgnoreAndReturn(cmock_retval) CORE_is_valid_app_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void CORE_is_valid_app_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define CORE_is_valid_app_StopIgnore() CORE_is_valid_app_CMockStopIgnore()
void CORE_is_valid_app_CMockStopIgnore(void);
#define CORE_is_valid_app_Expect() TEST_FAIL_MESSAGE("CORE_is_valid_app requires _ExpectAndReturn");
#define CORE_is_valid_app_ExpectAndReturn(cmock_retval) CORE_is_valid_app_CMockExpectAndReturn(__LINE__, cmock_retval)
void CORE_is_valid_app_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
typedef bool (* CMOCK_CORE_is_valid_app_CALLBACK)(int cmock_num_calls);
void CORE_is_valid_app_AddCallback(CMOCK_CORE_is_valid_app_CALLBACK Callback);
void CORE_is_valid_app_Stub(CMOCK_CORE_is_valid_app_CALLBACK Callback);
#define CORE_is_valid_app_StubWithCallback CORE_is_valid_app_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
