/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_BL_USART_DRV_H
#define _MOCK_BL_USART_DRV_H

#include "unity.h"
#include "bl_usart_drv.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_bl_usart_drv_Init(void);
void mock_bl_usart_drv_Destroy(void);
void mock_bl_usart_drv_Verify(void);




#define init_bl_usart_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("init_bl_usart requires _Ignore (not AndReturn)");
#define init_bl_usart_Ignore() init_bl_usart_CMockIgnore()
void init_bl_usart_CMockIgnore(void);
#define init_bl_usart_StopIgnore() init_bl_usart_CMockStopIgnore()
void init_bl_usart_CMockStopIgnore(void);
#define init_bl_usart_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("init_bl_usart requires _Expect (not AndReturn)");
#define init_bl_usart_Expect() init_bl_usart_CMockExpect(__LINE__)
void init_bl_usart_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_init_bl_usart_CALLBACK)(int cmock_num_calls);
void init_bl_usart_AddCallback(CMOCK_init_bl_usart_CALLBACK Callback);
void init_bl_usart_Stub(CMOCK_init_bl_usart_CALLBACK Callback);
#define init_bl_usart_StubWithCallback init_bl_usart_Stub
#define register_data_rx_cb_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("register_data_rx_cb requires _Ignore (not AndReturn)");
#define register_data_rx_cb_Ignore() register_data_rx_cb_CMockIgnore()
void register_data_rx_cb_CMockIgnore(void);
#define register_data_rx_cb_StopIgnore() register_data_rx_cb_CMockStopIgnore()
void register_data_rx_cb_CMockStopIgnore(void);
#define register_data_rx_cb_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("register_data_rx_cb requires _ExpectAnyArgs (not AndReturn)");
#define register_data_rx_cb_ExpectAnyArgs() register_data_rx_cb_CMockExpectAnyArgs(__LINE__)
void register_data_rx_cb_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define register_data_rx_cb_ExpectAndReturn(callback, cmock_retval) TEST_FAIL_MESSAGE("register_data_rx_cb requires _Expect (not AndReturn)");
#define register_data_rx_cb_Expect(callback) register_data_rx_cb_CMockExpect(__LINE__, callback)
void register_data_rx_cb_CMockExpect(UNITY_LINE_TYPE cmock_line, data_rx_cb_t callback);
typedef void (* CMOCK_register_data_rx_cb_CALLBACK)(data_rx_cb_t callback, int cmock_num_calls);
void register_data_rx_cb_AddCallback(CMOCK_register_data_rx_cb_CALLBACK Callback);
void register_data_rx_cb_Stub(CMOCK_register_data_rx_cb_CALLBACK Callback);
#define register_data_rx_cb_StubWithCallback register_data_rx_cb_Stub
#define deinit_bl_usart_periph_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("deinit_bl_usart_periph requires _Ignore (not AndReturn)");
#define deinit_bl_usart_periph_Ignore() deinit_bl_usart_periph_CMockIgnore()
void deinit_bl_usart_periph_CMockIgnore(void);
#define deinit_bl_usart_periph_StopIgnore() deinit_bl_usart_periph_CMockStopIgnore()
void deinit_bl_usart_periph_CMockStopIgnore(void);
#define deinit_bl_usart_periph_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("deinit_bl_usart_periph requires _Expect (not AndReturn)");
#define deinit_bl_usart_periph_Expect() deinit_bl_usart_periph_CMockExpect(__LINE__)
void deinit_bl_usart_periph_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_deinit_bl_usart_periph_CALLBACK)(int cmock_num_calls);
void deinit_bl_usart_periph_AddCallback(CMOCK_deinit_bl_usart_periph_CALLBACK Callback);
void deinit_bl_usart_periph_Stub(CMOCK_deinit_bl_usart_periph_CALLBACK Callback);
#define deinit_bl_usart_periph_StubWithCallback deinit_bl_usart_periph_Stub
#define deinit_bl_usart_clk_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("deinit_bl_usart_clk requires _Ignore (not AndReturn)");
#define deinit_bl_usart_clk_Ignore() deinit_bl_usart_clk_CMockIgnore()
void deinit_bl_usart_clk_CMockIgnore(void);
#define deinit_bl_usart_clk_StopIgnore() deinit_bl_usart_clk_CMockStopIgnore()
void deinit_bl_usart_clk_CMockStopIgnore(void);
#define deinit_bl_usart_clk_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("deinit_bl_usart_clk requires _Expect (not AndReturn)");
#define deinit_bl_usart_clk_Expect() deinit_bl_usart_clk_CMockExpect(__LINE__)
void deinit_bl_usart_clk_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_deinit_bl_usart_clk_CALLBACK)(int cmock_num_calls);
void deinit_bl_usart_clk_AddCallback(CMOCK_deinit_bl_usart_clk_CALLBACK Callback);
void deinit_bl_usart_clk_Stub(CMOCK_deinit_bl_usart_clk_CALLBACK Callback);
#define deinit_bl_usart_clk_StubWithCallback deinit_bl_usart_clk_Stub
#define send_byte_table_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("send_byte_table requires _Ignore (not AndReturn)");
#define send_byte_table_Ignore() send_byte_table_CMockIgnore()
void send_byte_table_CMockIgnore(void);
#define send_byte_table_StopIgnore() send_byte_table_CMockStopIgnore()
void send_byte_table_CMockStopIgnore(void);
#define send_byte_table_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("send_byte_table requires _ExpectAnyArgs (not AndReturn)");
#define send_byte_table_ExpectAnyArgs() send_byte_table_CMockExpectAnyArgs(__LINE__)
void send_byte_table_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define send_byte_table_ExpectAndReturn(d, l, cmock_retval) TEST_FAIL_MESSAGE("send_byte_table requires _Expect (not AndReturn)");
#define send_byte_table_Expect(d, l) send_byte_table_CMockExpect(__LINE__, d, l)
void send_byte_table_CMockExpect(UNITY_LINE_TYPE cmock_line, const uint8_t* d, size_t l);
typedef void (* CMOCK_send_byte_table_CALLBACK)(const uint8_t* d, size_t l, int cmock_num_calls);
void send_byte_table_AddCallback(CMOCK_send_byte_table_CALLBACK Callback);
void send_byte_table_Stub(CMOCK_send_byte_table_CALLBACK Callback);
#define send_byte_table_StubWithCallback send_byte_table_Stub
#define send_byte_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("send_byte requires _Ignore (not AndReturn)");
#define send_byte_Ignore() send_byte_CMockIgnore()
void send_byte_CMockIgnore(void);
#define send_byte_StopIgnore() send_byte_CMockStopIgnore()
void send_byte_CMockStopIgnore(void);
#define send_byte_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("send_byte requires _ExpectAnyArgs (not AndReturn)");
#define send_byte_ExpectAnyArgs() send_byte_CMockExpectAnyArgs(__LINE__)
void send_byte_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define send_byte_ExpectAndReturn(b, cmock_retval) TEST_FAIL_MESSAGE("send_byte requires _Expect (not AndReturn)");
#define send_byte_Expect(b) send_byte_CMockExpect(__LINE__, b)
void send_byte_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t b);
typedef void (* CMOCK_send_byte_CALLBACK)(uint8_t b, int cmock_num_calls);
void send_byte_AddCallback(CMOCK_send_byte_CALLBACK Callback);
void send_byte_Stub(CMOCK_send_byte_CALLBACK Callback);
#define send_byte_StubWithCallback send_byte_Stub
#define byte_transmission_complete_Ignore() TEST_FAIL_MESSAGE("byte_transmission_complete requires _IgnoreAndReturn");
#define byte_transmission_complete_IgnoreAndReturn(cmock_retval) byte_transmission_complete_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void byte_transmission_complete_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define byte_transmission_complete_StopIgnore() byte_transmission_complete_CMockStopIgnore()
void byte_transmission_complete_CMockStopIgnore(void);
#define byte_transmission_complete_Expect() TEST_FAIL_MESSAGE("byte_transmission_complete requires _ExpectAndReturn");
#define byte_transmission_complete_ExpectAndReturn(cmock_retval) byte_transmission_complete_CMockExpectAndReturn(__LINE__, cmock_retval)
void byte_transmission_complete_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
typedef bool (* CMOCK_byte_transmission_complete_CALLBACK)(int cmock_num_calls);
void byte_transmission_complete_AddCallback(CMOCK_byte_transmission_complete_CALLBACK Callback);
void byte_transmission_complete_Stub(CMOCK_byte_transmission_complete_CALLBACK Callback);
#define byte_transmission_complete_StubWithCallback byte_transmission_complete_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
