/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_bl_key_drv.h"

static const char* CMockString_bl_key_pressed = "bl_key_pressed";
static const char* CMockString_deinit_bl_key = "deinit_bl_key";
static const char* CMockString_deinit_bl_key_clk = "deinit_bl_key_clk";
static const char* CMockString_init_bl_key = "init_bl_key";

typedef struct _CMOCK_init_bl_key_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_init_bl_key_CALL_INSTANCE;

typedef struct _CMOCK_deinit_bl_key_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_deinit_bl_key_CALL_INSTANCE;

typedef struct _CMOCK_deinit_bl_key_clk_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_deinit_bl_key_clk_CALL_INSTANCE;

typedef struct _CMOCK_bl_key_pressed_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;

} CMOCK_bl_key_pressed_CALL_INSTANCE;

static struct mock_bl_key_drvInstance
{
  char init_bl_key_IgnoreBool;
  char init_bl_key_CallbackBool;
  CMOCK_init_bl_key_CALLBACK init_bl_key_CallbackFunctionPointer;
  int init_bl_key_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE init_bl_key_CallInstance;
  char deinit_bl_key_IgnoreBool;
  char deinit_bl_key_CallbackBool;
  CMOCK_deinit_bl_key_CALLBACK deinit_bl_key_CallbackFunctionPointer;
  int deinit_bl_key_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE deinit_bl_key_CallInstance;
  char deinit_bl_key_clk_IgnoreBool;
  char deinit_bl_key_clk_CallbackBool;
  CMOCK_deinit_bl_key_clk_CALLBACK deinit_bl_key_clk_CallbackFunctionPointer;
  int deinit_bl_key_clk_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE deinit_bl_key_clk_CallInstance;
  char bl_key_pressed_IgnoreBool;
  bool bl_key_pressed_FinalReturn;
  char bl_key_pressed_CallbackBool;
  CMOCK_bl_key_pressed_CALLBACK bl_key_pressed_CallbackFunctionPointer;
  int bl_key_pressed_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE bl_key_pressed_CallInstance;
} Mock;


void mock_bl_key_drv_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.init_bl_key_CallInstance;
  if (Mock.init_bl_key_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_init_bl_key);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.init_bl_key_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.deinit_bl_key_CallInstance;
  if (Mock.deinit_bl_key_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_deinit_bl_key);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.deinit_bl_key_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.deinit_bl_key_clk_CallInstance;
  if (Mock.deinit_bl_key_clk_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_deinit_bl_key_clk);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.deinit_bl_key_clk_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.bl_key_pressed_CallInstance;
  if (Mock.bl_key_pressed_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_bl_key_pressed);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.bl_key_pressed_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_bl_key_drv_Init(void)
{
  mock_bl_key_drv_Destroy();
}

void mock_bl_key_drv_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void init_bl_key(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_init_bl_key_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_init_bl_key);
  cmock_call_instance = (CMOCK_init_bl_key_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.init_bl_key_CallInstance);
  Mock.init_bl_key_CallInstance = CMock_Guts_MemNext(Mock.init_bl_key_CallInstance);
  if (Mock.init_bl_key_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.init_bl_key_CallbackBool &&
      Mock.init_bl_key_CallbackFunctionPointer != NULL)
  {
    Mock.init_bl_key_CallbackFunctionPointer(Mock.init_bl_key_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.init_bl_key_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_init_bl_key);
    Mock.init_bl_key_CallbackFunctionPointer(Mock.init_bl_key_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void init_bl_key_CMockIgnore(void)
{
  Mock.init_bl_key_IgnoreBool = (char)1;
}

void init_bl_key_CMockStopIgnore(void)
{
  Mock.init_bl_key_IgnoreBool = (char)0;
}

void init_bl_key_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_init_bl_key_CALL_INSTANCE));
  CMOCK_init_bl_key_CALL_INSTANCE* cmock_call_instance = (CMOCK_init_bl_key_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.init_bl_key_CallInstance = CMock_Guts_MemChain(Mock.init_bl_key_CallInstance, cmock_guts_index);
  Mock.init_bl_key_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void init_bl_key_AddCallback(CMOCK_init_bl_key_CALLBACK Callback)
{
  Mock.init_bl_key_IgnoreBool = (char)0;
  Mock.init_bl_key_CallbackBool = (char)1;
  Mock.init_bl_key_CallbackFunctionPointer = Callback;
}

void init_bl_key_Stub(CMOCK_init_bl_key_CALLBACK Callback)
{
  Mock.init_bl_key_IgnoreBool = (char)0;
  Mock.init_bl_key_CallbackBool = (char)0;
  Mock.init_bl_key_CallbackFunctionPointer = Callback;
}

void deinit_bl_key(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_deinit_bl_key_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_deinit_bl_key);
  cmock_call_instance = (CMOCK_deinit_bl_key_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.deinit_bl_key_CallInstance);
  Mock.deinit_bl_key_CallInstance = CMock_Guts_MemNext(Mock.deinit_bl_key_CallInstance);
  if (Mock.deinit_bl_key_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.deinit_bl_key_CallbackBool &&
      Mock.deinit_bl_key_CallbackFunctionPointer != NULL)
  {
    Mock.deinit_bl_key_CallbackFunctionPointer(Mock.deinit_bl_key_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.deinit_bl_key_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_deinit_bl_key);
    Mock.deinit_bl_key_CallbackFunctionPointer(Mock.deinit_bl_key_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void deinit_bl_key_CMockIgnore(void)
{
  Mock.deinit_bl_key_IgnoreBool = (char)1;
}

void deinit_bl_key_CMockStopIgnore(void)
{
  Mock.deinit_bl_key_IgnoreBool = (char)0;
}

void deinit_bl_key_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_deinit_bl_key_CALL_INSTANCE));
  CMOCK_deinit_bl_key_CALL_INSTANCE* cmock_call_instance = (CMOCK_deinit_bl_key_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.deinit_bl_key_CallInstance = CMock_Guts_MemChain(Mock.deinit_bl_key_CallInstance, cmock_guts_index);
  Mock.deinit_bl_key_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void deinit_bl_key_AddCallback(CMOCK_deinit_bl_key_CALLBACK Callback)
{
  Mock.deinit_bl_key_IgnoreBool = (char)0;
  Mock.deinit_bl_key_CallbackBool = (char)1;
  Mock.deinit_bl_key_CallbackFunctionPointer = Callback;
}

void deinit_bl_key_Stub(CMOCK_deinit_bl_key_CALLBACK Callback)
{
  Mock.deinit_bl_key_IgnoreBool = (char)0;
  Mock.deinit_bl_key_CallbackBool = (char)0;
  Mock.deinit_bl_key_CallbackFunctionPointer = Callback;
}

void deinit_bl_key_clk(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_deinit_bl_key_clk_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_deinit_bl_key_clk);
  cmock_call_instance = (CMOCK_deinit_bl_key_clk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.deinit_bl_key_clk_CallInstance);
  Mock.deinit_bl_key_clk_CallInstance = CMock_Guts_MemNext(Mock.deinit_bl_key_clk_CallInstance);
  if (Mock.deinit_bl_key_clk_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.deinit_bl_key_clk_CallbackBool &&
      Mock.deinit_bl_key_clk_CallbackFunctionPointer != NULL)
  {
    Mock.deinit_bl_key_clk_CallbackFunctionPointer(Mock.deinit_bl_key_clk_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.deinit_bl_key_clk_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_deinit_bl_key_clk);
    Mock.deinit_bl_key_clk_CallbackFunctionPointer(Mock.deinit_bl_key_clk_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void deinit_bl_key_clk_CMockIgnore(void)
{
  Mock.deinit_bl_key_clk_IgnoreBool = (char)1;
}

void deinit_bl_key_clk_CMockStopIgnore(void)
{
  Mock.deinit_bl_key_clk_IgnoreBool = (char)0;
}

void deinit_bl_key_clk_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_deinit_bl_key_clk_CALL_INSTANCE));
  CMOCK_deinit_bl_key_clk_CALL_INSTANCE* cmock_call_instance = (CMOCK_deinit_bl_key_clk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.deinit_bl_key_clk_CallInstance = CMock_Guts_MemChain(Mock.deinit_bl_key_clk_CallInstance, cmock_guts_index);
  Mock.deinit_bl_key_clk_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void deinit_bl_key_clk_AddCallback(CMOCK_deinit_bl_key_clk_CALLBACK Callback)
{
  Mock.deinit_bl_key_clk_IgnoreBool = (char)0;
  Mock.deinit_bl_key_clk_CallbackBool = (char)1;
  Mock.deinit_bl_key_clk_CallbackFunctionPointer = Callback;
}

void deinit_bl_key_clk_Stub(CMOCK_deinit_bl_key_clk_CALLBACK Callback)
{
  Mock.deinit_bl_key_clk_IgnoreBool = (char)0;
  Mock.deinit_bl_key_clk_CallbackBool = (char)0;
  Mock.deinit_bl_key_clk_CallbackFunctionPointer = Callback;
}

bool bl_key_pressed(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_bl_key_pressed_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_bl_key_pressed);
  cmock_call_instance = (CMOCK_bl_key_pressed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.bl_key_pressed_CallInstance);
  Mock.bl_key_pressed_CallInstance = CMock_Guts_MemNext(Mock.bl_key_pressed_CallInstance);
  if (Mock.bl_key_pressed_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.bl_key_pressed_FinalReturn;
    Mock.bl_key_pressed_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.bl_key_pressed_CallbackBool &&
      Mock.bl_key_pressed_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.bl_key_pressed_CallbackFunctionPointer(Mock.bl_key_pressed_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.bl_key_pressed_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_bl_key_pressed);
    cmock_call_instance->ReturnVal = Mock.bl_key_pressed_CallbackFunctionPointer(Mock.bl_key_pressed_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void bl_key_pressed_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_bl_key_pressed_CALL_INSTANCE));
  CMOCK_bl_key_pressed_CALL_INSTANCE* cmock_call_instance = (CMOCK_bl_key_pressed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.bl_key_pressed_CallInstance = CMock_Guts_MemChain(Mock.bl_key_pressed_CallInstance, cmock_guts_index);
  Mock.bl_key_pressed_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.bl_key_pressed_IgnoreBool = (char)1;
}

void bl_key_pressed_CMockStopIgnore(void)
{
  if(Mock.bl_key_pressed_IgnoreBool)
    Mock.bl_key_pressed_CallInstance = CMock_Guts_MemNext(Mock.bl_key_pressed_CallInstance);
  Mock.bl_key_pressed_IgnoreBool = (char)0;
}

void bl_key_pressed_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_bl_key_pressed_CALL_INSTANCE));
  CMOCK_bl_key_pressed_CALL_INSTANCE* cmock_call_instance = (CMOCK_bl_key_pressed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.bl_key_pressed_CallInstance = CMock_Guts_MemChain(Mock.bl_key_pressed_CallInstance, cmock_guts_index);
  Mock.bl_key_pressed_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void bl_key_pressed_AddCallback(CMOCK_bl_key_pressed_CALLBACK Callback)
{
  Mock.bl_key_pressed_IgnoreBool = (char)0;
  Mock.bl_key_pressed_CallbackBool = (char)1;
  Mock.bl_key_pressed_CallbackFunctionPointer = Callback;
}

void bl_key_pressed_Stub(CMOCK_bl_key_pressed_CALLBACK Callback)
{
  Mock.bl_key_pressed_IgnoreBool = (char)0;
  Mock.bl_key_pressed_CallbackBool = (char)0;
  Mock.bl_key_pressed_CallbackFunctionPointer = Callback;
}

