/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_core_drv.h"

static const char* CMockString_CORE_is_valid_app = "CORE_is_valid_app";
static const char* CMockString_callback = "callback";
static const char* CMockString_deinit_nvic = "deinit_nvic";
static const char* CMockString_deinit_sys_tick = "deinit_sys_tick";
static const char* CMockString_init_sys_tick = "init_sys_tick";
static const char* CMockString_jump_to_app = "jump_to_app";
static const char* CMockString_register_sysTick_cb = "register_sysTick_cb";
static const char* CMockString_system_reset = "system_reset";

typedef struct _CMOCK_init_sys_tick_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_init_sys_tick_CALL_INSTANCE;

typedef struct _CMOCK_deinit_sys_tick_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_deinit_sys_tick_CALL_INSTANCE;

typedef struct _CMOCK_deinit_nvic_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_deinit_nvic_CALL_INSTANCE;

typedef struct _CMOCK_register_sysTick_cb_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  SysTick_cb_t Expected_callback;

} CMOCK_register_sysTick_cb_CALL_INSTANCE;

typedef struct _CMOCK_jump_to_app_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_jump_to_app_CALL_INSTANCE;

typedef struct _CMOCK_system_reset_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_system_reset_CALL_INSTANCE;

typedef struct _CMOCK_CORE_is_valid_app_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  bool ReturnVal;

} CMOCK_CORE_is_valid_app_CALL_INSTANCE;

static struct mock_core_drvInstance
{
  char init_sys_tick_IgnoreBool;
  char init_sys_tick_CallbackBool;
  CMOCK_init_sys_tick_CALLBACK init_sys_tick_CallbackFunctionPointer;
  int init_sys_tick_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE init_sys_tick_CallInstance;
  char deinit_sys_tick_IgnoreBool;
  char deinit_sys_tick_CallbackBool;
  CMOCK_deinit_sys_tick_CALLBACK deinit_sys_tick_CallbackFunctionPointer;
  int deinit_sys_tick_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE deinit_sys_tick_CallInstance;
  char deinit_nvic_IgnoreBool;
  char deinit_nvic_CallbackBool;
  CMOCK_deinit_nvic_CALLBACK deinit_nvic_CallbackFunctionPointer;
  int deinit_nvic_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE deinit_nvic_CallInstance;
  char register_sysTick_cb_IgnoreBool;
  char register_sysTick_cb_CallbackBool;
  CMOCK_register_sysTick_cb_CALLBACK register_sysTick_cb_CallbackFunctionPointer;
  int register_sysTick_cb_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE register_sysTick_cb_CallInstance;
  char jump_to_app_IgnoreBool;
  char jump_to_app_CallbackBool;
  CMOCK_jump_to_app_CALLBACK jump_to_app_CallbackFunctionPointer;
  int jump_to_app_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE jump_to_app_CallInstance;
  char system_reset_IgnoreBool;
  char system_reset_CallbackBool;
  CMOCK_system_reset_CALLBACK system_reset_CallbackFunctionPointer;
  int system_reset_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE system_reset_CallInstance;
  char CORE_is_valid_app_IgnoreBool;
  bool CORE_is_valid_app_FinalReturn;
  char CORE_is_valid_app_CallbackBool;
  CMOCK_CORE_is_valid_app_CALLBACK CORE_is_valid_app_CallbackFunctionPointer;
  int CORE_is_valid_app_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE CORE_is_valid_app_CallInstance;
} Mock;


void mock_core_drv_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.init_sys_tick_CallInstance;
  if (Mock.init_sys_tick_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_init_sys_tick);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.init_sys_tick_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.deinit_sys_tick_CallInstance;
  if (Mock.deinit_sys_tick_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_deinit_sys_tick);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.deinit_sys_tick_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.deinit_nvic_CallInstance;
  if (Mock.deinit_nvic_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_deinit_nvic);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.deinit_nvic_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.register_sysTick_cb_CallInstance;
  if (Mock.register_sysTick_cb_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_register_sysTick_cb);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.register_sysTick_cb_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.jump_to_app_CallInstance;
  if (Mock.jump_to_app_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_jump_to_app);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.jump_to_app_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.system_reset_CallInstance;
  if (Mock.system_reset_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_system_reset);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.system_reset_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.CORE_is_valid_app_CallInstance;
  if (Mock.CORE_is_valid_app_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_CORE_is_valid_app);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.CORE_is_valid_app_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_core_drv_Init(void)
{
  mock_core_drv_Destroy();
}

void mock_core_drv_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void init_sys_tick(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_init_sys_tick_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_init_sys_tick);
  cmock_call_instance = (CMOCK_init_sys_tick_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.init_sys_tick_CallInstance);
  Mock.init_sys_tick_CallInstance = CMock_Guts_MemNext(Mock.init_sys_tick_CallInstance);
  if (Mock.init_sys_tick_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.init_sys_tick_CallbackBool &&
      Mock.init_sys_tick_CallbackFunctionPointer != NULL)
  {
    Mock.init_sys_tick_CallbackFunctionPointer(Mock.init_sys_tick_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.init_sys_tick_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_init_sys_tick);
    Mock.init_sys_tick_CallbackFunctionPointer(Mock.init_sys_tick_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void init_sys_tick_CMockIgnore(void)
{
  Mock.init_sys_tick_IgnoreBool = (char)1;
}

void init_sys_tick_CMockStopIgnore(void)
{
  Mock.init_sys_tick_IgnoreBool = (char)0;
}

void init_sys_tick_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_init_sys_tick_CALL_INSTANCE));
  CMOCK_init_sys_tick_CALL_INSTANCE* cmock_call_instance = (CMOCK_init_sys_tick_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.init_sys_tick_CallInstance = CMock_Guts_MemChain(Mock.init_sys_tick_CallInstance, cmock_guts_index);
  Mock.init_sys_tick_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void init_sys_tick_AddCallback(CMOCK_init_sys_tick_CALLBACK Callback)
{
  Mock.init_sys_tick_IgnoreBool = (char)0;
  Mock.init_sys_tick_CallbackBool = (char)1;
  Mock.init_sys_tick_CallbackFunctionPointer = Callback;
}

void init_sys_tick_Stub(CMOCK_init_sys_tick_CALLBACK Callback)
{
  Mock.init_sys_tick_IgnoreBool = (char)0;
  Mock.init_sys_tick_CallbackBool = (char)0;
  Mock.init_sys_tick_CallbackFunctionPointer = Callback;
}

void deinit_sys_tick(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_deinit_sys_tick_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_deinit_sys_tick);
  cmock_call_instance = (CMOCK_deinit_sys_tick_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.deinit_sys_tick_CallInstance);
  Mock.deinit_sys_tick_CallInstance = CMock_Guts_MemNext(Mock.deinit_sys_tick_CallInstance);
  if (Mock.deinit_sys_tick_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.deinit_sys_tick_CallbackBool &&
      Mock.deinit_sys_tick_CallbackFunctionPointer != NULL)
  {
    Mock.deinit_sys_tick_CallbackFunctionPointer(Mock.deinit_sys_tick_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.deinit_sys_tick_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_deinit_sys_tick);
    Mock.deinit_sys_tick_CallbackFunctionPointer(Mock.deinit_sys_tick_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void deinit_sys_tick_CMockIgnore(void)
{
  Mock.deinit_sys_tick_IgnoreBool = (char)1;
}

void deinit_sys_tick_CMockStopIgnore(void)
{
  Mock.deinit_sys_tick_IgnoreBool = (char)0;
}

void deinit_sys_tick_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_deinit_sys_tick_CALL_INSTANCE));
  CMOCK_deinit_sys_tick_CALL_INSTANCE* cmock_call_instance = (CMOCK_deinit_sys_tick_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.deinit_sys_tick_CallInstance = CMock_Guts_MemChain(Mock.deinit_sys_tick_CallInstance, cmock_guts_index);
  Mock.deinit_sys_tick_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void deinit_sys_tick_AddCallback(CMOCK_deinit_sys_tick_CALLBACK Callback)
{
  Mock.deinit_sys_tick_IgnoreBool = (char)0;
  Mock.deinit_sys_tick_CallbackBool = (char)1;
  Mock.deinit_sys_tick_CallbackFunctionPointer = Callback;
}

void deinit_sys_tick_Stub(CMOCK_deinit_sys_tick_CALLBACK Callback)
{
  Mock.deinit_sys_tick_IgnoreBool = (char)0;
  Mock.deinit_sys_tick_CallbackBool = (char)0;
  Mock.deinit_sys_tick_CallbackFunctionPointer = Callback;
}

void deinit_nvic(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_deinit_nvic_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_deinit_nvic);
  cmock_call_instance = (CMOCK_deinit_nvic_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.deinit_nvic_CallInstance);
  Mock.deinit_nvic_CallInstance = CMock_Guts_MemNext(Mock.deinit_nvic_CallInstance);
  if (Mock.deinit_nvic_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.deinit_nvic_CallbackBool &&
      Mock.deinit_nvic_CallbackFunctionPointer != NULL)
  {
    Mock.deinit_nvic_CallbackFunctionPointer(Mock.deinit_nvic_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.deinit_nvic_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_deinit_nvic);
    Mock.deinit_nvic_CallbackFunctionPointer(Mock.deinit_nvic_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void deinit_nvic_CMockIgnore(void)
{
  Mock.deinit_nvic_IgnoreBool = (char)1;
}

void deinit_nvic_CMockStopIgnore(void)
{
  Mock.deinit_nvic_IgnoreBool = (char)0;
}

void deinit_nvic_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_deinit_nvic_CALL_INSTANCE));
  CMOCK_deinit_nvic_CALL_INSTANCE* cmock_call_instance = (CMOCK_deinit_nvic_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.deinit_nvic_CallInstance = CMock_Guts_MemChain(Mock.deinit_nvic_CallInstance, cmock_guts_index);
  Mock.deinit_nvic_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void deinit_nvic_AddCallback(CMOCK_deinit_nvic_CALLBACK Callback)
{
  Mock.deinit_nvic_IgnoreBool = (char)0;
  Mock.deinit_nvic_CallbackBool = (char)1;
  Mock.deinit_nvic_CallbackFunctionPointer = Callback;
}

void deinit_nvic_Stub(CMOCK_deinit_nvic_CALLBACK Callback)
{
  Mock.deinit_nvic_IgnoreBool = (char)0;
  Mock.deinit_nvic_CallbackBool = (char)0;
  Mock.deinit_nvic_CallbackFunctionPointer = Callback;
}

void register_sysTick_cb(SysTick_cb_t callback)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_register_sysTick_cb_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_register_sysTick_cb);
  cmock_call_instance = (CMOCK_register_sysTick_cb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.register_sysTick_cb_CallInstance);
  Mock.register_sysTick_cb_CallInstance = CMock_Guts_MemNext(Mock.register_sysTick_cb_CallInstance);
  if (Mock.register_sysTick_cb_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.register_sysTick_cb_CallbackBool &&
      Mock.register_sysTick_cb_CallbackFunctionPointer != NULL)
  {
    Mock.register_sysTick_cb_CallbackFunctionPointer(callback, Mock.register_sysTick_cb_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_register_sysTick_cb,CMockString_callback);
    UNITY_TEST_ASSERT_EQUAL_MEMORY(&cmock_call_instance->Expected_callback, &callback, sizeof(SysTick_cb_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.register_sysTick_cb_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_register_sysTick_cb);
    Mock.register_sysTick_cb_CallbackFunctionPointer(callback, Mock.register_sysTick_cb_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_register_sysTick_cb(CMOCK_register_sysTick_cb_CALL_INSTANCE* cmock_call_instance, SysTick_cb_t callback);
void CMockExpectParameters_register_sysTick_cb(CMOCK_register_sysTick_cb_CALL_INSTANCE* cmock_call_instance, SysTick_cb_t callback)
{
  memcpy((void*)(&cmock_call_instance->Expected_callback), (const void*)(&callback),
         sizeof(SysTick_cb_t[sizeof(callback) == sizeof(SysTick_cb_t) ? 1 : -1])); /* add SysTick_cb_t to :treat_as_array if this causes an error */
}

void register_sysTick_cb_CMockIgnore(void)
{
  Mock.register_sysTick_cb_IgnoreBool = (char)1;
}

void register_sysTick_cb_CMockStopIgnore(void)
{
  Mock.register_sysTick_cb_IgnoreBool = (char)0;
}

void register_sysTick_cb_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_register_sysTick_cb_CALL_INSTANCE));
  CMOCK_register_sysTick_cb_CALL_INSTANCE* cmock_call_instance = (CMOCK_register_sysTick_cb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.register_sysTick_cb_CallInstance = CMock_Guts_MemChain(Mock.register_sysTick_cb_CallInstance, cmock_guts_index);
  Mock.register_sysTick_cb_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void register_sysTick_cb_CMockExpect(UNITY_LINE_TYPE cmock_line, SysTick_cb_t callback)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_register_sysTick_cb_CALL_INSTANCE));
  CMOCK_register_sysTick_cb_CALL_INSTANCE* cmock_call_instance = (CMOCK_register_sysTick_cb_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.register_sysTick_cb_CallInstance = CMock_Guts_MemChain(Mock.register_sysTick_cb_CallInstance, cmock_guts_index);
  Mock.register_sysTick_cb_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_register_sysTick_cb(cmock_call_instance, callback);
}

void register_sysTick_cb_AddCallback(CMOCK_register_sysTick_cb_CALLBACK Callback)
{
  Mock.register_sysTick_cb_IgnoreBool = (char)0;
  Mock.register_sysTick_cb_CallbackBool = (char)1;
  Mock.register_sysTick_cb_CallbackFunctionPointer = Callback;
}

void register_sysTick_cb_Stub(CMOCK_register_sysTick_cb_CALLBACK Callback)
{
  Mock.register_sysTick_cb_IgnoreBool = (char)0;
  Mock.register_sysTick_cb_CallbackBool = (char)0;
  Mock.register_sysTick_cb_CallbackFunctionPointer = Callback;
}

void jump_to_app(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_jump_to_app_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_jump_to_app);
  cmock_call_instance = (CMOCK_jump_to_app_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.jump_to_app_CallInstance);
  Mock.jump_to_app_CallInstance = CMock_Guts_MemNext(Mock.jump_to_app_CallInstance);
  if (Mock.jump_to_app_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.jump_to_app_CallbackBool &&
      Mock.jump_to_app_CallbackFunctionPointer != NULL)
  {
    Mock.jump_to_app_CallbackFunctionPointer(Mock.jump_to_app_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.jump_to_app_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_jump_to_app);
    Mock.jump_to_app_CallbackFunctionPointer(Mock.jump_to_app_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void jump_to_app_CMockIgnore(void)
{
  Mock.jump_to_app_IgnoreBool = (char)1;
}

void jump_to_app_CMockStopIgnore(void)
{
  Mock.jump_to_app_IgnoreBool = (char)0;
}

void jump_to_app_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_jump_to_app_CALL_INSTANCE));
  CMOCK_jump_to_app_CALL_INSTANCE* cmock_call_instance = (CMOCK_jump_to_app_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.jump_to_app_CallInstance = CMock_Guts_MemChain(Mock.jump_to_app_CallInstance, cmock_guts_index);
  Mock.jump_to_app_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void jump_to_app_AddCallback(CMOCK_jump_to_app_CALLBACK Callback)
{
  Mock.jump_to_app_IgnoreBool = (char)0;
  Mock.jump_to_app_CallbackBool = (char)1;
  Mock.jump_to_app_CallbackFunctionPointer = Callback;
}

void jump_to_app_Stub(CMOCK_jump_to_app_CALLBACK Callback)
{
  Mock.jump_to_app_IgnoreBool = (char)0;
  Mock.jump_to_app_CallbackBool = (char)0;
  Mock.jump_to_app_CallbackFunctionPointer = Callback;
}

void system_reset(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_system_reset_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_system_reset);
  cmock_call_instance = (CMOCK_system_reset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.system_reset_CallInstance);
  Mock.system_reset_CallInstance = CMock_Guts_MemNext(Mock.system_reset_CallInstance);
  if (Mock.system_reset_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.system_reset_CallbackBool &&
      Mock.system_reset_CallbackFunctionPointer != NULL)
  {
    Mock.system_reset_CallbackFunctionPointer(Mock.system_reset_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.system_reset_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_system_reset);
    Mock.system_reset_CallbackFunctionPointer(Mock.system_reset_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void system_reset_CMockIgnore(void)
{
  Mock.system_reset_IgnoreBool = (char)1;
}

void system_reset_CMockStopIgnore(void)
{
  Mock.system_reset_IgnoreBool = (char)0;
}

void system_reset_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_system_reset_CALL_INSTANCE));
  CMOCK_system_reset_CALL_INSTANCE* cmock_call_instance = (CMOCK_system_reset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.system_reset_CallInstance = CMock_Guts_MemChain(Mock.system_reset_CallInstance, cmock_guts_index);
  Mock.system_reset_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void system_reset_AddCallback(CMOCK_system_reset_CALLBACK Callback)
{
  Mock.system_reset_IgnoreBool = (char)0;
  Mock.system_reset_CallbackBool = (char)1;
  Mock.system_reset_CallbackFunctionPointer = Callback;
}

void system_reset_Stub(CMOCK_system_reset_CALLBACK Callback)
{
  Mock.system_reset_IgnoreBool = (char)0;
  Mock.system_reset_CallbackBool = (char)0;
  Mock.system_reset_CallbackFunctionPointer = Callback;
}

bool CORE_is_valid_app(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_CORE_is_valid_app_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_CORE_is_valid_app);
  cmock_call_instance = (CMOCK_CORE_is_valid_app_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.CORE_is_valid_app_CallInstance);
  Mock.CORE_is_valid_app_CallInstance = CMock_Guts_MemNext(Mock.CORE_is_valid_app_CallInstance);
  if (Mock.CORE_is_valid_app_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.CORE_is_valid_app_FinalReturn;
    Mock.CORE_is_valid_app_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.CORE_is_valid_app_CallbackBool &&
      Mock.CORE_is_valid_app_CallbackFunctionPointer != NULL)
  {
    bool cmock_cb_ret = Mock.CORE_is_valid_app_CallbackFunctionPointer(Mock.CORE_is_valid_app_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.CORE_is_valid_app_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_CORE_is_valid_app);
    cmock_call_instance->ReturnVal = Mock.CORE_is_valid_app_CallbackFunctionPointer(Mock.CORE_is_valid_app_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CORE_is_valid_app_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CORE_is_valid_app_CALL_INSTANCE));
  CMOCK_CORE_is_valid_app_CALL_INSTANCE* cmock_call_instance = (CMOCK_CORE_is_valid_app_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CORE_is_valid_app_CallInstance = CMock_Guts_MemChain(Mock.CORE_is_valid_app_CallInstance, cmock_guts_index);
  Mock.CORE_is_valid_app_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.CORE_is_valid_app_IgnoreBool = (char)1;
}

void CORE_is_valid_app_CMockStopIgnore(void)
{
  if(Mock.CORE_is_valid_app_IgnoreBool)
    Mock.CORE_is_valid_app_CallInstance = CMock_Guts_MemNext(Mock.CORE_is_valid_app_CallInstance);
  Mock.CORE_is_valid_app_IgnoreBool = (char)0;
}

void CORE_is_valid_app_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CORE_is_valid_app_CALL_INSTANCE));
  CMOCK_CORE_is_valid_app_CALL_INSTANCE* cmock_call_instance = (CMOCK_CORE_is_valid_app_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CORE_is_valid_app_CallInstance = CMock_Guts_MemChain(Mock.CORE_is_valid_app_CallInstance, cmock_guts_index);
  Mock.CORE_is_valid_app_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void CORE_is_valid_app_AddCallback(CMOCK_CORE_is_valid_app_CALLBACK Callback)
{
  Mock.CORE_is_valid_app_IgnoreBool = (char)0;
  Mock.CORE_is_valid_app_CallbackBool = (char)1;
  Mock.CORE_is_valid_app_CallbackFunctionPointer = Callback;
}

void CORE_is_valid_app_Stub(CMOCK_CORE_is_valid_app_CALLBACK Callback)
{
  Mock.CORE_is_valid_app_IgnoreBool = (char)0;
  Mock.CORE_is_valid_app_CallbackBool = (char)0;
  Mock.CORE_is_valid_app_CallbackFunctionPointer = Callback;
}

