/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_bl_status_led_drv.h"

static const char* CMockString_deinit_bl_status_led_clk = "deinit_bl_status_led_clk";
static const char* CMockString_deinit_bl_status_led_port = "deinit_bl_status_led_port";
static const char* CMockString_init_bl_status_led = "init_bl_status_led";
static const char* CMockString_toggle_bl_led = "toggle_bl_led";

typedef struct _CMOCK_init_bl_status_led_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_init_bl_status_led_CALL_INSTANCE;

typedef struct _CMOCK_deinit_bl_status_led_port_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_deinit_bl_status_led_port_CALL_INSTANCE;

typedef struct _CMOCK_deinit_bl_status_led_clk_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_deinit_bl_status_led_clk_CALL_INSTANCE;

typedef struct _CMOCK_toggle_bl_led_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_toggle_bl_led_CALL_INSTANCE;

static struct mock_bl_status_led_drvInstance
{
  char init_bl_status_led_IgnoreBool;
  char init_bl_status_led_CallbackBool;
  CMOCK_init_bl_status_led_CALLBACK init_bl_status_led_CallbackFunctionPointer;
  int init_bl_status_led_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE init_bl_status_led_CallInstance;
  char deinit_bl_status_led_port_IgnoreBool;
  char deinit_bl_status_led_port_CallbackBool;
  CMOCK_deinit_bl_status_led_port_CALLBACK deinit_bl_status_led_port_CallbackFunctionPointer;
  int deinit_bl_status_led_port_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE deinit_bl_status_led_port_CallInstance;
  char deinit_bl_status_led_clk_IgnoreBool;
  char deinit_bl_status_led_clk_CallbackBool;
  CMOCK_deinit_bl_status_led_clk_CALLBACK deinit_bl_status_led_clk_CallbackFunctionPointer;
  int deinit_bl_status_led_clk_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE deinit_bl_status_led_clk_CallInstance;
  char toggle_bl_led_IgnoreBool;
  char toggle_bl_led_CallbackBool;
  CMOCK_toggle_bl_led_CALLBACK toggle_bl_led_CallbackFunctionPointer;
  int toggle_bl_led_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE toggle_bl_led_CallInstance;
} Mock;


void mock_bl_status_led_drv_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.init_bl_status_led_CallInstance;
  if (Mock.init_bl_status_led_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_init_bl_status_led);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.init_bl_status_led_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.deinit_bl_status_led_port_CallInstance;
  if (Mock.deinit_bl_status_led_port_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_deinit_bl_status_led_port);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.deinit_bl_status_led_port_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.deinit_bl_status_led_clk_CallInstance;
  if (Mock.deinit_bl_status_led_clk_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_deinit_bl_status_led_clk);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.deinit_bl_status_led_clk_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.toggle_bl_led_CallInstance;
  if (Mock.toggle_bl_led_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_toggle_bl_led);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.toggle_bl_led_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_bl_status_led_drv_Init(void)
{
  mock_bl_status_led_drv_Destroy();
}

void mock_bl_status_led_drv_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void init_bl_status_led(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_init_bl_status_led_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_init_bl_status_led);
  cmock_call_instance = (CMOCK_init_bl_status_led_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.init_bl_status_led_CallInstance);
  Mock.init_bl_status_led_CallInstance = CMock_Guts_MemNext(Mock.init_bl_status_led_CallInstance);
  if (Mock.init_bl_status_led_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.init_bl_status_led_CallbackBool &&
      Mock.init_bl_status_led_CallbackFunctionPointer != NULL)
  {
    Mock.init_bl_status_led_CallbackFunctionPointer(Mock.init_bl_status_led_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.init_bl_status_led_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_init_bl_status_led);
    Mock.init_bl_status_led_CallbackFunctionPointer(Mock.init_bl_status_led_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void init_bl_status_led_CMockIgnore(void)
{
  Mock.init_bl_status_led_IgnoreBool = (char)1;
}

void init_bl_status_led_CMockStopIgnore(void)
{
  Mock.init_bl_status_led_IgnoreBool = (char)0;
}

void init_bl_status_led_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_init_bl_status_led_CALL_INSTANCE));
  CMOCK_init_bl_status_led_CALL_INSTANCE* cmock_call_instance = (CMOCK_init_bl_status_led_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.init_bl_status_led_CallInstance = CMock_Guts_MemChain(Mock.init_bl_status_led_CallInstance, cmock_guts_index);
  Mock.init_bl_status_led_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void init_bl_status_led_AddCallback(CMOCK_init_bl_status_led_CALLBACK Callback)
{
  Mock.init_bl_status_led_IgnoreBool = (char)0;
  Mock.init_bl_status_led_CallbackBool = (char)1;
  Mock.init_bl_status_led_CallbackFunctionPointer = Callback;
}

void init_bl_status_led_Stub(CMOCK_init_bl_status_led_CALLBACK Callback)
{
  Mock.init_bl_status_led_IgnoreBool = (char)0;
  Mock.init_bl_status_led_CallbackBool = (char)0;
  Mock.init_bl_status_led_CallbackFunctionPointer = Callback;
}

void deinit_bl_status_led_port(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_deinit_bl_status_led_port_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_deinit_bl_status_led_port);
  cmock_call_instance = (CMOCK_deinit_bl_status_led_port_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.deinit_bl_status_led_port_CallInstance);
  Mock.deinit_bl_status_led_port_CallInstance = CMock_Guts_MemNext(Mock.deinit_bl_status_led_port_CallInstance);
  if (Mock.deinit_bl_status_led_port_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.deinit_bl_status_led_port_CallbackBool &&
      Mock.deinit_bl_status_led_port_CallbackFunctionPointer != NULL)
  {
    Mock.deinit_bl_status_led_port_CallbackFunctionPointer(Mock.deinit_bl_status_led_port_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.deinit_bl_status_led_port_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_deinit_bl_status_led_port);
    Mock.deinit_bl_status_led_port_CallbackFunctionPointer(Mock.deinit_bl_status_led_port_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void deinit_bl_status_led_port_CMockIgnore(void)
{
  Mock.deinit_bl_status_led_port_IgnoreBool = (char)1;
}

void deinit_bl_status_led_port_CMockStopIgnore(void)
{
  Mock.deinit_bl_status_led_port_IgnoreBool = (char)0;
}

void deinit_bl_status_led_port_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_deinit_bl_status_led_port_CALL_INSTANCE));
  CMOCK_deinit_bl_status_led_port_CALL_INSTANCE* cmock_call_instance = (CMOCK_deinit_bl_status_led_port_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.deinit_bl_status_led_port_CallInstance = CMock_Guts_MemChain(Mock.deinit_bl_status_led_port_CallInstance, cmock_guts_index);
  Mock.deinit_bl_status_led_port_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void deinit_bl_status_led_port_AddCallback(CMOCK_deinit_bl_status_led_port_CALLBACK Callback)
{
  Mock.deinit_bl_status_led_port_IgnoreBool = (char)0;
  Mock.deinit_bl_status_led_port_CallbackBool = (char)1;
  Mock.deinit_bl_status_led_port_CallbackFunctionPointer = Callback;
}

void deinit_bl_status_led_port_Stub(CMOCK_deinit_bl_status_led_port_CALLBACK Callback)
{
  Mock.deinit_bl_status_led_port_IgnoreBool = (char)0;
  Mock.deinit_bl_status_led_port_CallbackBool = (char)0;
  Mock.deinit_bl_status_led_port_CallbackFunctionPointer = Callback;
}

void deinit_bl_status_led_clk(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_deinit_bl_status_led_clk_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_deinit_bl_status_led_clk);
  cmock_call_instance = (CMOCK_deinit_bl_status_led_clk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.deinit_bl_status_led_clk_CallInstance);
  Mock.deinit_bl_status_led_clk_CallInstance = CMock_Guts_MemNext(Mock.deinit_bl_status_led_clk_CallInstance);
  if (Mock.deinit_bl_status_led_clk_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.deinit_bl_status_led_clk_CallbackBool &&
      Mock.deinit_bl_status_led_clk_CallbackFunctionPointer != NULL)
  {
    Mock.deinit_bl_status_led_clk_CallbackFunctionPointer(Mock.deinit_bl_status_led_clk_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.deinit_bl_status_led_clk_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_deinit_bl_status_led_clk);
    Mock.deinit_bl_status_led_clk_CallbackFunctionPointer(Mock.deinit_bl_status_led_clk_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void deinit_bl_status_led_clk_CMockIgnore(void)
{
  Mock.deinit_bl_status_led_clk_IgnoreBool = (char)1;
}

void deinit_bl_status_led_clk_CMockStopIgnore(void)
{
  Mock.deinit_bl_status_led_clk_IgnoreBool = (char)0;
}

void deinit_bl_status_led_clk_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_deinit_bl_status_led_clk_CALL_INSTANCE));
  CMOCK_deinit_bl_status_led_clk_CALL_INSTANCE* cmock_call_instance = (CMOCK_deinit_bl_status_led_clk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.deinit_bl_status_led_clk_CallInstance = CMock_Guts_MemChain(Mock.deinit_bl_status_led_clk_CallInstance, cmock_guts_index);
  Mock.deinit_bl_status_led_clk_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void deinit_bl_status_led_clk_AddCallback(CMOCK_deinit_bl_status_led_clk_CALLBACK Callback)
{
  Mock.deinit_bl_status_led_clk_IgnoreBool = (char)0;
  Mock.deinit_bl_status_led_clk_CallbackBool = (char)1;
  Mock.deinit_bl_status_led_clk_CallbackFunctionPointer = Callback;
}

void deinit_bl_status_led_clk_Stub(CMOCK_deinit_bl_status_led_clk_CALLBACK Callback)
{
  Mock.deinit_bl_status_led_clk_IgnoreBool = (char)0;
  Mock.deinit_bl_status_led_clk_CallbackBool = (char)0;
  Mock.deinit_bl_status_led_clk_CallbackFunctionPointer = Callback;
}

void toggle_bl_led(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_toggle_bl_led_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_toggle_bl_led);
  cmock_call_instance = (CMOCK_toggle_bl_led_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.toggle_bl_led_CallInstance);
  Mock.toggle_bl_led_CallInstance = CMock_Guts_MemNext(Mock.toggle_bl_led_CallInstance);
  if (Mock.toggle_bl_led_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.toggle_bl_led_CallbackBool &&
      Mock.toggle_bl_led_CallbackFunctionPointer != NULL)
  {
    Mock.toggle_bl_led_CallbackFunctionPointer(Mock.toggle_bl_led_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.toggle_bl_led_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_toggle_bl_led);
    Mock.toggle_bl_led_CallbackFunctionPointer(Mock.toggle_bl_led_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void toggle_bl_led_CMockIgnore(void)
{
  Mock.toggle_bl_led_IgnoreBool = (char)1;
}

void toggle_bl_led_CMockStopIgnore(void)
{
  Mock.toggle_bl_led_IgnoreBool = (char)0;
}

void toggle_bl_led_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_toggle_bl_led_CALL_INSTANCE));
  CMOCK_toggle_bl_led_CALL_INSTANCE* cmock_call_instance = (CMOCK_toggle_bl_led_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.toggle_bl_led_CallInstance = CMock_Guts_MemChain(Mock.toggle_bl_led_CallInstance, cmock_guts_index);
  Mock.toggle_bl_led_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void toggle_bl_led_AddCallback(CMOCK_toggle_bl_led_CALLBACK Callback)
{
  Mock.toggle_bl_led_IgnoreBool = (char)0;
  Mock.toggle_bl_led_CallbackBool = (char)1;
  Mock.toggle_bl_led_CallbackFunctionPointer = Callback;
}

void toggle_bl_led_Stub(CMOCK_toggle_bl_led_CALLBACK Callback)
{
  Mock.toggle_bl_led_IgnoreBool = (char)0;
  Mock.toggle_bl_led_CallbackBool = (char)0;
  Mock.toggle_bl_led_CallbackFunctionPointer = Callback;
}

