/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_aes.h"

static const char* CMockString_AES_CBC_decrypt_buffer = "AES_CBC_decrypt_buffer";
static const char* CMockString_AES_CBC_init = "AES_CBC_init";
static const char* CMockString_buf = "buf";
static const char* CMockString_iv = "iv";
static const char* CMockString_key = "key";
static const char* CMockString_length = "length";

typedef struct _CMOCK_AES_CBC_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  const uint8_t* Expected_key;
  const uint8_t* Expected_iv;

} CMOCK_AES_CBC_init_CALL_INSTANCE;

typedef struct _CMOCK_AES_CBC_decrypt_buffer_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint8_t* Expected_buf;
  uint32_t Expected_length;
  char ReturnThruPtr_buf_Used;
  uint8_t const* ReturnThruPtr_buf_Val;
  size_t ReturnThruPtr_buf_Size;

} CMOCK_AES_CBC_decrypt_buffer_CALL_INSTANCE;

static struct mock_aesInstance
{
  char AES_CBC_init_IgnoreBool;
  char AES_CBC_init_CallbackBool;
  CMOCK_AES_CBC_init_CALLBACK AES_CBC_init_CallbackFunctionPointer;
  int AES_CBC_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE AES_CBC_init_CallInstance;
  char AES_CBC_decrypt_buffer_IgnoreBool;
  char AES_CBC_decrypt_buffer_CallbackBool;
  CMOCK_AES_CBC_decrypt_buffer_CALLBACK AES_CBC_decrypt_buffer_CallbackFunctionPointer;
  int AES_CBC_decrypt_buffer_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE AES_CBC_decrypt_buffer_CallInstance;
} Mock;


void mock_aes_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.AES_CBC_init_CallInstance;
  if (Mock.AES_CBC_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_AES_CBC_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.AES_CBC_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.AES_CBC_decrypt_buffer_CallInstance;
  if (Mock.AES_CBC_decrypt_buffer_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_AES_CBC_decrypt_buffer);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.AES_CBC_decrypt_buffer_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_aes_Init(void)
{
  mock_aes_Destroy();
}

void mock_aes_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void AES_CBC_init(const uint8_t* key, const uint8_t* iv)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_AES_CBC_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_AES_CBC_init);
  cmock_call_instance = (CMOCK_AES_CBC_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.AES_CBC_init_CallInstance);
  Mock.AES_CBC_init_CallInstance = CMock_Guts_MemNext(Mock.AES_CBC_init_CallInstance);
  if (Mock.AES_CBC_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.AES_CBC_init_CallbackBool &&
      Mock.AES_CBC_init_CallbackFunctionPointer != NULL)
  {
    Mock.AES_CBC_init_CallbackFunctionPointer(key, iv, Mock.AES_CBC_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_AES_CBC_init,CMockString_key);
    if (cmock_call_instance->Expected_key == NULL)
      { UNITY_TEST_ASSERT_NULL(key, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_key, key, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_AES_CBC_init,CMockString_iv);
    if (cmock_call_instance->Expected_iv == NULL)
      { UNITY_TEST_ASSERT_NULL(iv, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_iv, iv, 1, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.AES_CBC_init_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_AES_CBC_init);
    Mock.AES_CBC_init_CallbackFunctionPointer(key, iv, Mock.AES_CBC_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_AES_CBC_init(CMOCK_AES_CBC_init_CALL_INSTANCE* cmock_call_instance, const uint8_t* key, const uint8_t* iv);
void CMockExpectParameters_AES_CBC_init(CMOCK_AES_CBC_init_CALL_INSTANCE* cmock_call_instance, const uint8_t* key, const uint8_t* iv)
{
  cmock_call_instance->Expected_key = key;
  cmock_call_instance->Expected_iv = iv;
}

void AES_CBC_init_CMockIgnore(void)
{
  Mock.AES_CBC_init_IgnoreBool = (char)1;
}

void AES_CBC_init_CMockStopIgnore(void)
{
  Mock.AES_CBC_init_IgnoreBool = (char)0;
}

void AES_CBC_init_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_AES_CBC_init_CALL_INSTANCE));
  CMOCK_AES_CBC_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_AES_CBC_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.AES_CBC_init_CallInstance = CMock_Guts_MemChain(Mock.AES_CBC_init_CallInstance, cmock_guts_index);
  Mock.AES_CBC_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void AES_CBC_init_CMockExpect(UNITY_LINE_TYPE cmock_line, const uint8_t* key, const uint8_t* iv)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_AES_CBC_init_CALL_INSTANCE));
  CMOCK_AES_CBC_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_AES_CBC_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.AES_CBC_init_CallInstance = CMock_Guts_MemChain(Mock.AES_CBC_init_CallInstance, cmock_guts_index);
  Mock.AES_CBC_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_AES_CBC_init(cmock_call_instance, key, iv);
}

void AES_CBC_init_AddCallback(CMOCK_AES_CBC_init_CALLBACK Callback)
{
  Mock.AES_CBC_init_IgnoreBool = (char)0;
  Mock.AES_CBC_init_CallbackBool = (char)1;
  Mock.AES_CBC_init_CallbackFunctionPointer = Callback;
}

void AES_CBC_init_Stub(CMOCK_AES_CBC_init_CALLBACK Callback)
{
  Mock.AES_CBC_init_IgnoreBool = (char)0;
  Mock.AES_CBC_init_CallbackBool = (char)0;
  Mock.AES_CBC_init_CallbackFunctionPointer = Callback;
}

void AES_CBC_decrypt_buffer(uint8_t* buf, uint32_t length)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_AES_CBC_decrypt_buffer_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_AES_CBC_decrypt_buffer);
  cmock_call_instance = (CMOCK_AES_CBC_decrypt_buffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.AES_CBC_decrypt_buffer_CallInstance);
  Mock.AES_CBC_decrypt_buffer_CallInstance = CMock_Guts_MemNext(Mock.AES_CBC_decrypt_buffer_CallInstance);
  if (Mock.AES_CBC_decrypt_buffer_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.AES_CBC_decrypt_buffer_CallbackBool &&
      Mock.AES_CBC_decrypt_buffer_CallbackFunctionPointer != NULL)
  {
    Mock.AES_CBC_decrypt_buffer_CallbackFunctionPointer(buf, length, Mock.AES_CBC_decrypt_buffer_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_AES_CBC_decrypt_buffer,CMockString_buf);
    if (cmock_call_instance->Expected_buf == NULL)
      { UNITY_TEST_ASSERT_NULL(buf, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_buf, buf, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_AES_CBC_decrypt_buffer,CMockString_length);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_length, length, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.AES_CBC_decrypt_buffer_CallbackFunctionPointer != NULL)
  {
    UNITY_SET_DETAIL(CMockString_AES_CBC_decrypt_buffer);
    Mock.AES_CBC_decrypt_buffer_CallbackFunctionPointer(buf, length, Mock.AES_CBC_decrypt_buffer_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_buf_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(buf, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)buf, (const void*)cmock_call_instance->ReturnThruPtr_buf_Val,
      cmock_call_instance->ReturnThruPtr_buf_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_AES_CBC_decrypt_buffer(CMOCK_AES_CBC_decrypt_buffer_CALL_INSTANCE* cmock_call_instance, uint8_t* buf, uint32_t length);
void CMockExpectParameters_AES_CBC_decrypt_buffer(CMOCK_AES_CBC_decrypt_buffer_CALL_INSTANCE* cmock_call_instance, uint8_t* buf, uint32_t length)
{
  cmock_call_instance->Expected_buf = buf;
  cmock_call_instance->ReturnThruPtr_buf_Used = 0;
  cmock_call_instance->Expected_length = length;
}

void AES_CBC_decrypt_buffer_CMockIgnore(void)
{
  Mock.AES_CBC_decrypt_buffer_IgnoreBool = (char)1;
}

void AES_CBC_decrypt_buffer_CMockStopIgnore(void)
{
  Mock.AES_CBC_decrypt_buffer_IgnoreBool = (char)0;
}

void AES_CBC_decrypt_buffer_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_AES_CBC_decrypt_buffer_CALL_INSTANCE));
  CMOCK_AES_CBC_decrypt_buffer_CALL_INSTANCE* cmock_call_instance = (CMOCK_AES_CBC_decrypt_buffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.AES_CBC_decrypt_buffer_CallInstance = CMock_Guts_MemChain(Mock.AES_CBC_decrypt_buffer_CallInstance, cmock_guts_index);
  Mock.AES_CBC_decrypt_buffer_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void AES_CBC_decrypt_buffer_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t* buf, uint32_t length)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_AES_CBC_decrypt_buffer_CALL_INSTANCE));
  CMOCK_AES_CBC_decrypt_buffer_CALL_INSTANCE* cmock_call_instance = (CMOCK_AES_CBC_decrypt_buffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.AES_CBC_decrypt_buffer_CallInstance = CMock_Guts_MemChain(Mock.AES_CBC_decrypt_buffer_CallInstance, cmock_guts_index);
  Mock.AES_CBC_decrypt_buffer_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_AES_CBC_decrypt_buffer(cmock_call_instance, buf, length);
}

void AES_CBC_decrypt_buffer_AddCallback(CMOCK_AES_CBC_decrypt_buffer_CALLBACK Callback)
{
  Mock.AES_CBC_decrypt_buffer_IgnoreBool = (char)0;
  Mock.AES_CBC_decrypt_buffer_CallbackBool = (char)1;
  Mock.AES_CBC_decrypt_buffer_CallbackFunctionPointer = Callback;
}

void AES_CBC_decrypt_buffer_Stub(CMOCK_AES_CBC_decrypt_buffer_CALLBACK Callback)
{
  Mock.AES_CBC_decrypt_buffer_IgnoreBool = (char)0;
  Mock.AES_CBC_decrypt_buffer_CallbackBool = (char)0;
  Mock.AES_CBC_decrypt_buffer_CallbackFunctionPointer = Callback;
}

void AES_CBC_decrypt_buffer_CMockReturnMemThruPtr_buf(UNITY_LINE_TYPE cmock_line, uint8_t const* buf, size_t cmock_size)
{
  CMOCK_AES_CBC_decrypt_buffer_CALL_INSTANCE* cmock_call_instance = (CMOCK_AES_CBC_decrypt_buffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.AES_CBC_decrypt_buffer_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_buf_Used = 1;
  cmock_call_instance->ReturnThruPtr_buf_Val = buf;
  cmock_call_instance->ReturnThruPtr_buf_Size = cmock_size;
}

