/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_BL_STATUS_LED_DRV_H
#define _MOCK_BL_STATUS_LED_DRV_H

#include "unity.h"
#include "bl_status_led_drv.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_bl_status_led_drv_Init(void);
void mock_bl_status_led_drv_Destroy(void);
void mock_bl_status_led_drv_Verify(void);




#define init_bl_status_led_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("init_bl_status_led requires _Ignore (not AndReturn)");
#define init_bl_status_led_Ignore() init_bl_status_led_CMockIgnore()
void init_bl_status_led_CMockIgnore(void);
#define init_bl_status_led_StopIgnore() init_bl_status_led_CMockStopIgnore()
void init_bl_status_led_CMockStopIgnore(void);
#define init_bl_status_led_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("init_bl_status_led requires _Expect (not AndReturn)");
#define init_bl_status_led_Expect() init_bl_status_led_CMockExpect(__LINE__)
void init_bl_status_led_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_init_bl_status_led_CALLBACK)(int cmock_num_calls);
void init_bl_status_led_AddCallback(CMOCK_init_bl_status_led_CALLBACK Callback);
void init_bl_status_led_Stub(CMOCK_init_bl_status_led_CALLBACK Callback);
#define init_bl_status_led_StubWithCallback init_bl_status_led_Stub
#define deinit_bl_status_led_port_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("deinit_bl_status_led_port requires _Ignore (not AndReturn)");
#define deinit_bl_status_led_port_Ignore() deinit_bl_status_led_port_CMockIgnore()
void deinit_bl_status_led_port_CMockIgnore(void);
#define deinit_bl_status_led_port_StopIgnore() deinit_bl_status_led_port_CMockStopIgnore()
void deinit_bl_status_led_port_CMockStopIgnore(void);
#define deinit_bl_status_led_port_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("deinit_bl_status_led_port requires _Expect (not AndReturn)");
#define deinit_bl_status_led_port_Expect() deinit_bl_status_led_port_CMockExpect(__LINE__)
void deinit_bl_status_led_port_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_deinit_bl_status_led_port_CALLBACK)(int cmock_num_calls);
void deinit_bl_status_led_port_AddCallback(CMOCK_deinit_bl_status_led_port_CALLBACK Callback);
void deinit_bl_status_led_port_Stub(CMOCK_deinit_bl_status_led_port_CALLBACK Callback);
#define deinit_bl_status_led_port_StubWithCallback deinit_bl_status_led_port_Stub
#define deinit_bl_status_led_clk_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("deinit_bl_status_led_clk requires _Ignore (not AndReturn)");
#define deinit_bl_status_led_clk_Ignore() deinit_bl_status_led_clk_CMockIgnore()
void deinit_bl_status_led_clk_CMockIgnore(void);
#define deinit_bl_status_led_clk_StopIgnore() deinit_bl_status_led_clk_CMockStopIgnore()
void deinit_bl_status_led_clk_CMockStopIgnore(void);
#define deinit_bl_status_led_clk_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("deinit_bl_status_led_clk requires _Expect (not AndReturn)");
#define deinit_bl_status_led_clk_Expect() deinit_bl_status_led_clk_CMockExpect(__LINE__)
void deinit_bl_status_led_clk_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_deinit_bl_status_led_clk_CALLBACK)(int cmock_num_calls);
void deinit_bl_status_led_clk_AddCallback(CMOCK_deinit_bl_status_led_clk_CALLBACK Callback);
void deinit_bl_status_led_clk_Stub(CMOCK_deinit_bl_status_led_clk_CALLBACK Callback);
#define deinit_bl_status_led_clk_StubWithCallback deinit_bl_status_led_clk_Stub
#define toggle_bl_led_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("toggle_bl_led requires _Ignore (not AndReturn)");
#define toggle_bl_led_Ignore() toggle_bl_led_CMockIgnore()
void toggle_bl_led_CMockIgnore(void);
#define toggle_bl_led_StopIgnore() toggle_bl_led_CMockStopIgnore()
void toggle_bl_led_CMockStopIgnore(void);
#define toggle_bl_led_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("toggle_bl_led requires _Expect (not AndReturn)");
#define toggle_bl_led_Expect() toggle_bl_led_CMockExpect(__LINE__)
void toggle_bl_led_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_toggle_bl_led_CALLBACK)(int cmock_num_calls);
void toggle_bl_led_AddCallback(CMOCK_toggle_bl_led_CALLBACK Callback);
void toggle_bl_led_Stub(CMOCK_toggle_bl_led_CALLBACK Callback);
#define toggle_bl_led_StubWithCallback toggle_bl_led_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
